In [602]:
import pandas as pd
import numpy as np

import datetime

In [603]:
file_path='C://Users//sneha//anaconda_projects//Customer_360//'

In [604]:
customer_df=pd.read_csv(file_path+'CUSTOMERS.csv')
geo_location_df=pd.read_csv(file_path+'GEO_LOCATION.csv')
order_items_df=pd.read_csv(file_path+'ORDER_ITEMS.csv')
order_payments_df=pd.read_csv(file_path+'ORDER_PAYMENTS.csv')
order_review_rating_df=pd.read_csv(file_path+'ORDER_REVIEW_RATINGS.csv')
orders_df=pd.read_csv(file_path+'ORDERS.csv')
products_df=pd.read_csv(file_path+'PRODUCTS.csv')
sellers_df=pd.read_csv(file_path+'SELLERS.csv')

In [605]:
#check for data type

In [606]:
''''''
customer_df.head(1)

,customer_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,Adilabad,Andhra Pradesh

In [607]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_zip_code_prefix  99441 non-null  int64
 2   customer_city             99441 non-null  object
 3   customer_state            99441 non-null  object
dtypes: int64(1), object(3)
memory usage: 3.0+ MB

In [608]:
''''''
geo_location_df.head(1)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,Akkarampalle,Andhra Pradesh

In [609]:
geo_location_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19015 entries, 0 to 19014
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   geolocation_zip_code_prefix  19015 non-null  int64
 1   geolocation_lat              19015 non-null  float64
 2   geolocation_lng              19015 non-null  float64
 3   geolocation_city             19015 non-null  object
 4   geolocation_state            19015 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 742.9+ KB

In [610]:
''''''
order_items_df.head(1)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,9/19/2017 9:45,58.9,13.29

In [611]:
'''we have to convert shipping_limit_date to date time formate'''

'we have to convert shipping_limit_date to date time formate'

In [612]:
order_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [613]:
''''''
order_payments_df.head(1)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33

In [614]:
order_payments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [615]:
''''''
order_review_rating_df.head(1)

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,1/18/2018 0:00,1/18/2018 21:46

In [616]:
order_review_rating_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   review_id                100000 non-null  object
 1   order_id                 100000 non-null  object
 2   review_score             100000 non-null  int64
 3   review_creation_date     100000 non-null  object
 4   review_answer_timestamp  100000 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [617]:
'''we have to convert review_creation_date,review_answer_timestamp to date_time'''

'we have to convert review_creation_date,review_answer_timestamp to date_time'

In [618]:
''''''
orders_df.head(1)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,10/2/2017 10:56,10/2/2017 11:07,10/4/2017 19:55,10/10/2017 21:25,10/18/2017 0:00

In [619]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [620]:
'''we have to convert order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,
order_delivered_customer_date,order_estimated_delivery_date to date_time formate'''

'we have to convert order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,\norder_delivered_customer_date,order_estimated_delivery_date to date_time formate'

In [621]:
''''''
products_df.head(1)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,Perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0

In [622]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32328 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [623]:
''''''
sellers_df.head(1)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Alwal,Andhra Pradesh

In [624]:
sellers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3038 non-null   object
 3   seller_state            3038 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [625]:

'''
customer_df----------------no
geo_location_df------------no
order_items_df-------------yes
order_payments_df----------no
order_review_rating_df-----yes
orders_df------------------yes
products_df----------------no
sellers_df-----------------no
'''

'\ncustomer_df----------------no\ngeo_location_df------------no\norder_items_df-------------yes\norder_payments_df----------no\norder_review_rating_df-----yes\norders_df------------------yes\nproducts_df----------------no\nsellers_df-----------------no\n'

In [626]:
'''for order_items_df['shipping_limit_date']'''
order_items_df.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [627]:
order_items_df['shipping_limit_date']=order_items_df['shipping_limit_date'].astype(str)

In [628]:
order_items_df['shipping_limit_date']=pd.to_datetime(order_items_df['shipping_limit_date'])

In [629]:
order_items_df['shipping_limit_date']=order_items_df['shipping_limit_date'].dt.strftime('%Y-%m-%d')

In [630]:
order_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [631]:
order_items_df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13,199.90,18.14

In [632]:
order_items_df['shipping_limit_date']=order_items_df['shipping_limit_date'].astype(str)

In [633]:
order_items_df['shipping_limit_date']=pd.to_datetime(order_items_df['shipping_limit_date'])

In [634]:
order_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

In [635]:
order_items_df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13,199.90,18.14

In [636]:
'''for order_review_rating_df['review_creation_date'], 
order_review_rating_df['review_answer_timestamp']'''
order_review_rating_df.columns

Index(['review_id', 'order_id', 'review_score', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [637]:
order_review_rating_df['review_creation_date']=order_review_rating_df['review_creation_date']\
                                                .astype(str)

In [638]:
order_review_rating_df['review_answer_timestamp']=order_review_rating_df['review_answer_timestamp']\
                                                  .astype(str)

In [639]:
order_review_rating_df['review_creation_date']=pd.to_datetime\
                                                (order_review_rating_df['review_creation_date'])

In [640]:
order_review_rating_df['review_answer_timestamp']=pd.to_datetime\
                                                (order_review_rating_df['review_answer_timestamp'])

In [641]:
order_review_rating_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   review_id                100000 non-null  object
 1   order_id                 100000 non-null  object
 2   review_score             100000 non-null  int64
 3   review_creation_date     100000 non-null  datetime64[ns]
 4   review_answer_timestamp  100000 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 3.8+ MB

In [642]:
order_review_rating_df.head(1)

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,2018-01-18,2018-01-18 21:46:00

In [643]:
order_review_rating_df['review_creation_date']=order_review_rating_df['review_creation_date']\
                                                .dt.strftime('%Y-%m-%d')

In [644]:
order_review_rating_df['review_answer_timestamp']=order_review_rating_df['review_answer_timestamp']\
                                                    .dt.strftime('%Y-%m-%d')

In [645]:
order_review_rating_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   review_id                100000 non-null  object
 1   order_id                 100000 non-null  object
 2   review_score             100000 non-null  int64
 3   review_creation_date     100000 non-null  object
 4   review_answer_timestamp  100000 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [646]:
order_review_rating_df['review_creation_date']=order_review_rating_df['review_creation_date']\
                                                .astype(str)
order_review_rating_df['review_answer_timestamp']=order_review_rating_df['review_answer_timestamp']\
                                                  .astype(str)

In [647]:
order_review_rating_df['review_creation_date']=pd.to_datetime\
                                                (order_review_rating_df['review_creation_date'])
order_review_rating_df['review_answer_timestamp']=pd.to_datetime\
                                                (order_review_rating_df['review_answer_timestamp'])

In [648]:
order_review_rating_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   review_id                100000 non-null  object
 1   order_id                 100000 non-null  object
 2   review_score             100000 non-null  int64
 3   review_creation_date     100000 non-null  datetime64[ns]
 4   review_answer_timestamp  100000 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 3.8+ MB

In [649]:
order_review_rating_df.head(1)

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,2018-01-18,2018-01-18

In [650]:
'''for orders_df['order_purchase_timestamp'],orders_df['order_approved_at'],
orders_df['order_delivered_carrier_date'],orders_df['order_delivered_customer_date'],
orders_df['order_estimated_delivery_date'] to date_time'''
orders_df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [651]:
orders_df['order_purchase_timestamp']=orders_df['order_purchase_timestamp'].astype(str)
orders_df['order_approved_at']=orders_df['order_approved_at'].astype(str)
orders_df['order_delivered_carrier_date']=orders_df['order_delivered_carrier_date'].astype(str)
orders_df['order_delivered_customer_date']=orders_df['order_delivered_customer_date'].astype(str)
orders_df['order_estimated_delivery_date']=orders_df['order_estimated_delivery_date'].astype(str)

In [652]:
orders_df['order_purchase_timestamp']=pd.to_datetime(orders_df['order_purchase_timestamp'])
orders_df['order_approved_at']=pd.to_datetime(orders_df['order_approved_at'])
orders_df['order_delivered_carrier_date']=pd.to_datetime(orders_df['order_delivered_carrier_date'])
orders_df['order_delivered_customer_date']=pd.to_datetime(orders_df['order_delivered_customer_date'])
orders_df['order_estimated_delivery_date']=pd.to_datetime(orders_df['order_estimated_delivery_date'])

In [653]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [654]:
orders_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26

In [655]:
orders_df['order_purchase_timestamp']=orders_df['order_purchase_timestamp'].dt.strftime('%Y-%m-%d')
orders_df['order_approved_at']=orders_df['order_approved_at'].dt.strftime('%Y-%m-%d')
orders_df['order_delivered_carrier_date']=orders_df['order_delivered_carrier_date'].dt.strftime('%Y-%m-%d')
orders_df['order_delivered_customer_date']=orders_df['order_delivered_customer_date'].dt.strftime('%Y-%m-%d')
orders_df['order_estimated_delivery_date']=orders_df['order_estimated_delivery_date'].dt.strftime('%Y-%m-%d')

In [656]:
orders_df['order_purchase_timestamp']=orders_df['order_purchase_timestamp'].astype(str)
orders_df['order_approved_at']=orders_df['order_approved_at'].astype(str)
orders_df['order_delivered_carrier_date']=orders_df['order_delivered_carrier_date'].astype(str)
orders_df['order_delivered_customer_date']=orders_df['order_delivered_customer_date'].astype(str)
orders_df['order_estimated_delivery_date']=orders_df['order_estimated_delivery_date'].astype(str)

In [657]:
orders_df['order_purchase_timestamp']=pd.to_datetime(orders_df['order_purchase_timestamp'])
orders_df['order_approved_at']=pd.to_datetime(orders_df['order_approved_at'])
orders_df['order_delivered_carrier_date']=pd.to_datetime(orders_df['order_delivered_carrier_date'])
orders_df['order_delivered_customer_date']=pd.to_datetime(orders_df['order_delivered_customer_date'])
orders_df['order_estimated_delivery_date']=pd.to_datetime(orders_df['order_estimated_delivery_date'])

In [658]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [659]:
orders_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24,2018-07-26,2018-07-26,2018-08-07,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08,2018-08-08,2018-08-08,2018-08-17,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18,2017-11-18,2017-11-22,2017-12-02,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13,2018-02-13,2018-02-14,2018-02-16,2018-02-26

In [660]:
#check for duplicate

In [661]:
'''
customer_df----------------no
geo_location_df------------no
order_items_df-------------no
order_payments_df----------no
order_review_rating_df-----no
orders_df------------------no
products_df----------------no
sellers_df-----------------no
'''

'\ncustomer_df----------------no\ngeo_location_df------------no\norder_items_df-------------no\norder_payments_df----------no\norder_review_rating_df-----no\norders_df------------------no\nproducts_df----------------no\nsellers_df-----------------no\n'

In [662]:
customer_df.duplicated().sum()

np.int64(0)

In [663]:
geo_location_df.duplicated().sum()

np.int64(0)

In [664]:
order_items_df.duplicated().sum()

np.int64(0)

In [665]:
order_payments_df.duplicated().sum()

np.int64(0)

In [666]:
order_review_rating_df.duplicated().sum()

np.int64(0)

In [667]:
orders_df.duplicated().sum()

np.int64(0)

In [668]:
products_df.duplicated().sum()

np.int64(0)

In [669]:
sellers_df.duplicated().sum()

np.int64(0)

In [670]:
#check for null

In [671]:
'''
customer_df----------------no
geo_location_df------------no
order_items_df-------------no
order_payments_df----------no
order_review_rating_df-----no
orders_df------------------yes
products_df----------------yes
sellers_df-----------------yes
'''

'\ncustomer_df----------------no\ngeo_location_df------------no\norder_items_df-------------no\norder_payments_df----------no\norder_review_rating_df-----no\norders_df------------------yes\nproducts_df----------------yes\nsellers_df-----------------yes\n'

In [672]:
customer_df.isna().sum()

customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [673]:
geo_location_df.isna().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [674]:
order_items_df.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [675]:
order_payments_df.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [676]:
order_review_rating_df.isna().sum()

review_id                  0
order_id                   0
review_score               0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [677]:
orders_df.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [678]:
'''orders_df have orders_df['order_approved_at'],orders_df['order_delivered_carrier_date'],
  orders_df['order_delivered_customer_date']'''

"orders_df have orders_df['order_approved_at'],orders_df['order_delivered_carrier_date'],\n  orders_df['order_delivered_customer_date']"

In [679]:
products_df.isna().sum()

product_id                      0
product_category_name         623
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [680]:
'''products_df['product_category_name'],products_df['product_name_lenght'],
products_df['product_description_lenght'],products_df['product_photos_qty'],
products_df['product_weight_g'],products_df['product_length_cm'],
products_df['product_height_cm'],products_df['product_width_cm']
'''

"products_df['product_category_name'],products_df['product_name_lenght'],\nproducts_df['product_description_lenght'],products_df['product_photos_qty'],\nproducts_df['product_weight_g'],products_df['product_length_cm'],\nproducts_df['product_height_cm'],products_df['product_width_cm']\n"

In [681]:
products_df.head(3)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,Perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,Art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,Sports_Leisure,46.0,250.0,1.0,154.0,18.0,9.0,15.0

In [682]:
sellers_df.isna().sum()

seller_id                  0
seller_zip_code_prefix     0
seller_city               57
seller_state              57
dtype: int64

In [683]:
'''sellers_df['seller_city'],sellers_df['seller_state']'''

"sellers_df['seller_city'],sellers_df['seller_state']"

In [684]:
sellers_df.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Alwal,Andhra Pradesh
1,d1b65fc7debc3361ea86b5f14c68d2e2,13023,Alwal,Andhra Pradesh
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,Badepalle,Andhra Pradesh
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,Akkarampalle,Andhra Pradesh
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,Koratla,Andhra Pradesh

In [685]:
'''orders_df have orders_df['order_approved_at'],orders_df['order_delivered_carrier_date'],
  orders_df['order_delivered_customer_date']'''

"orders_df have orders_df['order_approved_at'],orders_df['order_delivered_carrier_date'],\n  orders_df['order_delivered_customer_date']"

In [686]:
orders_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24,2018-07-26,2018-07-26,2018-08-07,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08,2018-08-08,2018-08-08,2018-08-17,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18,2017-11-18,2017-11-22,2017-12-02,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13,2018-02-13,2018-02-14,2018-02-16,2018-02-26

In [687]:
'''we will keep it as it is'''

'we will keep it as it is'

In [688]:
'''products_df['product_category_name'],products_df['product_name_lenght'],
products_df['product_description_lenght'],products_df['product_photos_qty'],
products_df['product_weight_g'],products_df['product_length_cm'],
products_df['product_height_cm'],products_df['product_width_cm']
'''

"products_df['product_category_name'],products_df['product_name_lenght'],\nproducts_df['product_description_lenght'],products_df['product_photos_qty'],\nproducts_df['product_weight_g'],products_df['product_length_cm'],\nproducts_df['product_height_cm'],products_df['product_width_cm']\n"

In [689]:
products_df.isna().sum()

product_id                      0
product_category_name         623
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [690]:
products_df.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,Perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,Art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,Sports_Leisure,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,Baby,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,Housewares,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [691]:
products_df.loc[:,'product_category_name'].fillna('Unknown',inplace=True)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\1094432738.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products_df.loc[:,'product_category_name'].fillna('Unknown',inplace=True)

In [692]:
products_df['product_name_lenght'].fillna(products_df['product_name_lenght'].median(),inplace=True)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\2700893870.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products_df['product_name_lenght'].fillna(products_df['product_name_lenght'].median(),inplace=True)

In [693]:
products_df['product_description_lenght'].fillna(products_df['product_description_lenght'].median(),
                                                 inplace=True)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\3468990873.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products_df['product_description_lenght'].fillna(products_df['product_description_lenght'].median(),

In [694]:
products_df['product_photos_qty'].fillna(products_df['product_photos_qty'].mean(),inplace=True)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\822556293.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products_df['product_photos_qty'].fillna(products_df['product_photos_qty'].mean(),inplace=True)

In [695]:
products_df['product_weight_g'].fillna(products_df['product_weight_g'].mean(),inplace=True)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\4026807670.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products_df['product_weight_g'].fillna(products_df['product_weight_g'].mean(),inplace=True)

In [696]:
products_df['product_length_cm'].fillna(products_df['product_length_cm'].mean(0),inplace=True)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\392635691.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products_df['product_length_cm'].fillna(products_df['product_length_cm'].mean(0),inplace=True)

In [697]:
products_df['product_height_cm'].fillna(products_df['product_height_cm'].mean(),inplace=True)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\1155677882.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products_df['product_height_cm'].fillna(products_df['product_height_cm'].mean(),inplace=True)

In [698]:
products_df['product_width_cm'].fillna(products_df['product_width_cm'].mean(),inplace=True)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\1208781623.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products_df['product_width_cm'].fillna(products_df['product_width_cm'].mean(),inplace=True)

In [699]:
products_df.isna().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [700]:
'''sellers_df['seller_city'],sellers_df['seller_state']'''

"sellers_df['seller_city'],sellers_df['seller_state']"

In [701]:
sellers_df.isna().sum()

seller_id                  0
seller_zip_code_prefix     0
seller_city               57
seller_state              57
dtype: int64

In [702]:
sellers_df['seller_city'].fillna('Unknown',inplace=True)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\2242799004.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sellers_df['seller_city'].fillna('Unknown',inplace=True)

In [703]:
sellers_df['seller_state'].fillna('Unknown',inplace=True)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\472424852.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sellers_df['seller_state'].fillna('Unknown',inplace=True)

In [704]:
sellers_df.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [705]:
orders_df.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [706]:
#use two years of data (recent data – Nov-2016 to Oct-2018) and use 
#period-1 as Nov-2016 to Oct-2017 and 
#period-2 as Nov-2017 to October -2018

#we only have to do it for oorders_df because it has a transation details

In [707]:
'''
customer_df----------------no
geo_location_df------------no
order_items_df-------------no
order_payments_df----------no
order_review_rating_df-----no
orders_df------------------yes
products_df----------------no
sellers_df-----------------no
'''

'\ncustomer_df----------------no\ngeo_location_df------------no\norder_items_df-------------no\norder_payments_df----------no\norder_review_rating_df-----no\norders_df------------------yes\nproducts_df----------------no\nsellers_df-----------------no\n'

In [708]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [709]:
'''yes we have to do for orders['order_purchase_timestamp']'''

"yes we have to do for orders['order_purchase_timestamp']"

In [710]:
#use two years of data (recent data – Nov-2016 to Oct-2018) and use 
#period-1 as Nov-2016 to Oct-2017 and 
#period-2 as Nov-2017 to October -2018

In [711]:
'''for orders_df['order_purchase_timestamp']'''
orders_df.head(1)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18

In [712]:
orders_df=orders_df.loc[\
                        (orders_df['order_purchase_timestamp']>='2016-11-01')&
                   (orders_df['order_purchase_timestamp']<='2018-10-31' )]

In [713]:
orders_df['order_purchase_timestamp'].min()

Timestamp('2016-12-23 00:00:00')

In [714]:
orders_df['order_purchase_timestamp'].max()

Timestamp('2018-10-17 00:00:00')

In [715]:
orders_df['order_purchase_timestamp_period_flag']=\
                            np.where(orders_df['order_purchase_timestamp']<='2017-10-31','P1','P2')

In [716]:
orders_df.head(1)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_timestamp_period_flag
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,P1

In [717]:
orders_df['order_purchase_timestamp_period_flag'].value_counts()

order_purchase_timestamp_period_flag
P2    67228
P1    31885
Name: count, dtype: int64

In [718]:
master_table=orders_df.merge(customer_df,left_on='customer_id',right_on='customer_id',how='left')

In [719]:
master_table=master_table.merge(geo_location_df,left_on='customer_zip_code_prefix',
                  right_on='geolocation_zip_code_prefix',how='left')

In [720]:
master_table=master_table.merge(order_items_df,left_on='order_id',right_on='order_id',
                  how='left')

In [721]:
master_table=master_table.merge(order_payments_df,left_on='order_id',right_on='order_id',
                  how='left')

In [722]:
master_table=master_table.merge(order_review_rating_df,left_on='order_id',right_on='order_id',
                  how='left')

In [723]:
master_table=master_table.merge(products_df,left_on='product_id',right_on='product_id',
                  how='left')

In [724]:
master_table=master_table.merge(sellers_df,left_on='seller_id',right_on='seller_id',
                  how='left')

In [725]:
master_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'geolocation_zip_code_prefix',
       'geolocation_lat', 'geolocation_lng', 'geolocation_city',
       'geolocation_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value', 'review_id',
       'review_score', 'review_creation_date', 'review_answer_timestamp',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state'],
      dtype='object')

In [726]:
#no_baskets= Number of baskets (all orders in one day is equal to basket)
#            -count(distinct no. of order dates)

In [727]:
master_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'geolocation_zip_code_prefix',
       'geolocation_lat', 'geolocation_lng', 'geolocation_city',
       'geolocation_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value', 'review_id',
       'review_score', 'review_creation_date', 'review_answer_timestamp',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state'],
      dtype='object')

In [728]:
no_baskets=orders_df.groupby(['customer_id']).agg\
    (no_baskets=('order_purchase_timestamp','nunique')).reset_index()

In [729]:
no_baskets.head(1)

                        customer_id  no_baskets
0  00012a2ce6f8dcda20d059ce98491703           1

In [730]:
#sale_amount=Total revenue from customer--Sum(sale_amount)

In [731]:
master_table.head(1)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_timestamp_period_flag,customer_zip_code_prefix,...,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,P1,3149,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,Chhuikhadan,Chhattisgarh

In [732]:
sale_amount=master_table.groupby(['customer_id']).agg\
            (sale_amount=('payment_value','sum')).reset_index()

In [733]:
sale_amount.head(1)

                        customer_id  sale_amount
0  00012a2ce6f8dcda20d059ce98491703       114.74

In [734]:
#sale_amount_p1=Total revenue from customer in period1--Sum(sale_amount) in period1

In [735]:
total_p1=master_table.loc[master_table['order_purchase_timestamp_period_flag']=='P1']

In [736]:
sale_amount_p1=total_p1.groupby(['customer_id']).agg\
                (sale_amount_p1=('payment_value','sum')).reset_index()

In [737]:
sale_amount_p1.head(1)

                        customer_id  sale_amount_p1
0  000161a058600d5901f007fab4c27140           67.41

In [738]:
#sale_amount_p2

In [739]:
total_p2=master_table.loc[master_table['order_purchase_timestamp_period_flag']=='P2']

In [740]:
sale_amount_p2=total_p2.groupby(['customer_id']).agg\
                (sale_amount_p2=('payment_value','sum')).reset_index()

In [741]:
sale_amount_p2.head(1)

                        customer_id  sale_amount_p2
0  00012a2ce6f8dcda20d059ce98491703          114.74

In [742]:
#act_amt=Actual sale amount---sum( sale_price * sale_number)
#sale_price=total_amount
#sale_number=order_item_id
#payment_value=sale_amount

In [743]:
master_table['total_amount']=master_table['price']+master_table['freight_value']

In [744]:
master_table['act_amt']=master_table['order_item_id']*master_table['total_amount']

In [745]:
master_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'geolocation_zip_code_prefix',
       'geolocation_lat', 'geolocation_lng', 'geolocation_city',
       'geolocation_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value', 'review_id',
       'review_score', 'review_creation_date', 'review_answer_timestamp',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state', 'total_amount',
       'act_amt'],
      dtype='object')

In [746]:
#cost_amt=Total Cost of products--sum(payment_value * sale_number)

In [747]:
master_table['cost_amt']=master_table['payment_value']*master_table['order_item_id']

In [748]:
master_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'geolocation_zip_code_prefix',
       'geolocation_lat', 'geolocation_lng', 'geolocation_city',
       'geolocation_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value', 'review_id',
       'review_score', 'review_creation_date', 'review_answer_timestamp',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state', 'total_amount',
       'act_amt', 'cost_amt'],
      dtype='object')

In [749]:
master_table.head(1)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_timestamp_period_flag,customer_zip_code_prefix,...,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,total_amount,act_amt,cost_amt
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,P1,3149,...,500.0,19.0,8.0,13.0,9350.0,Chhuikhadan,Chhattisgarh,38.71,38.71,18.12

In [750]:
#margin=margin on products(Sale_amount - Cost_amount)--Sum(sale_amount)-sum(cost_price * sale_number)

In [783]:
master_table['margin']=(master_table['payment_value']-master_table['cost_amt']).round(2)

In [784]:
master_table.head(1)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_timestamp_period_flag,customer_zip_code_prefix,...,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,total_amount,act_amt,cost_amt,margin,week_flag,promotion_flag
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,P1,3149,...,13.0,9350.0,Chhuikhadan,Chhattisgarh,38.71,38.71,18.12,0.0,weekday,promotion

In [785]:
#no_baskets_weekend=Number of trips(baskets) in weekends(Saturday & Sunday)

In [786]:
master_table['week_flag']=np.where(master_table['order_purchase_timestamp'].dt.dayofweek<=5,\
                                   'weekday','weekend')

In [787]:
master_table['week_flag'].value_counts()

week_flag
weekday    104685
weekend     14057
Name: count, dtype: int64

In [788]:
weekend_count=master_table.loc[master_table['week_flag']=='weekend']

In [789]:
no_baskets_weekend=weekend_count.groupby(['customer_id']).agg\
                (no_baskets_weekend=('order_purchase_timestamp','nunique')).reset_index()

In [790]:
no_baskets_weekend.head(1)

                        customer_id  no_baskets_weekend
0  000161a058600d5901f007fab4c27140                   1

In [791]:
#no_baskets_w_promo_prds=Number of trips(baskets) with at least one free sample product
#create promotion_flag

In [792]:
master_table['promotion_flag']=np.where(master_table['payment_sequential']<=2,'promotion',\
                                        'no_promotion')

In [793]:
promotion_count=master_table.loc[master_table['promotion_flag']=='promotion']

In [794]:
no_baskets_w_promo_prds=promotion_count.groupby(['customer_id']).agg\
                        (no_baskets_w_promo_prds=('promotion_flag','count')).reset_index()

In [795]:
no_baskets_w_promo_prds.head()

                        customer_id  no_baskets_w_promo_prds
0  00012a2ce6f8dcda20d059ce98491703                        1
1  000161a058600d5901f007fab4c27140                        1
2  0001fd6190edaaf884bcaf3d49edf079                        1
3  0002414f95344307404f0ace7a26f1d5                        1
4  000379cdec625522490c315e70c7a9fb                        1

In [796]:
#quantiy=Total number of items----sum(sale_number)

In [797]:
quantity=master_table.groupby(['customer_id']).agg(quantity=('order_item_id','sum')).reset_index()

In [798]:
quantity.head(1)

                        customer_id  quantity
0  00012a2ce6f8dcda20d059ce98491703       1.0

In [ ]:
#discount=Total Discount Amount---sum( sale_price * sale_number) - sum(sale_amount)
#sale_price=total_amount
#sale_number=order_item_id
#sale_amount=payment_value

In [804]:
master_table['discount']=(master_table['act_amt']-master_table['payment_value']).round(2)

In [805]:
master_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'geolocation_zip_code_prefix',
       'geolocation_lat', 'geolocation_lng', 'geolocation_city',
       'geolocation_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value', 'review_id',
       'review_score', 'review_creation_date', 'review_answer_timestamp',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state', 'total_amount',
       'act_amt', 'cost_amt', 'margin', 'week_flag', 'promotion_flag',
       'discount'],
      dtype='object')

In [806]:
#discount_items=Number of discount items where discount >0--count(discount>0)
master_table['discount'].value_counts()

discount
 0.00      93121
 100.00      229
 50.00       216
 0.01         85
-77.57        74
           ...
 30.82         1
-129.53        1
 161.42        1
 8.34          1
 36.71         1
Name: count, Length: 16304, dtype: int64

In [808]:
discount_item_count=master_table.loc[master_table['discount']>0]

In [809]:
discount_item=discount_item_count.groupby(['customer_id']).agg\
                                        (discount_item=('discount','count')).reset_index()

In [810]:
discount_item.head(1)

                        customer_id  discount_item
0  000e943451fc2788ca6ac98a682f2f49              4

In [ ]:
#no_prds=Number of products---Sum(no.of sku)
#we will name the product to others where the product count is less than 1000

In [834]:
no_prds=master_table.groupby(['customer_id']).agg(no_prods=('product_id','count')).reset_index()

In [836]:
no_prds.head(1)

                        customer_id  no_prods
0  00012a2ce6f8dcda20d059ce98491703         1

In [ ]:
#no_prds_weekend---Number of products purchased in week ends

In [837]:
no_prds_weekend=weekend_count.groupby(['customer_id']).agg\
                                        (no_prds_weekend=('product_id','count')).reset_index()

In [838]:
no_prds_weekend.head(1)

                        customer_id  no_prds_weekend
0  000161a058600d5901f007fab4c27140                1

In [ ]:
#no_prds_promo=Number of promo products purchased

In [839]:
no_prds_promo=promotion_count.groupby(['customer_id']).agg\
                                        (no_prds_promo=('product_id','count')).reset_index()

In [840]:
no_prds_promo.head(1)

                        customer_id  no_prds_promo
0  00012a2ce6f8dcda20d059ce98491703              1

In [ ]:
#Total number of products
'''
cat_prd_cnt_Food
cat_prd_cnt_Kitchen_clean
cat_prd_cnt_Beauty
cat_prd_cnt_Imported_food
cat_prd_cnt_Drinks
cat_prd_cnt_Mother_child
cat_prd_cnt_Home
cat_prd_cnt_Nutrition
cat_prd_cnt_HH_Electrical
cat_prd_cnt_Office_sup_Comuters
cat_prd_cnt_Digital
cat_prd_cnt_Mobile
cat_prd_cnt_Car_prods
cat_prd_cnt_Cloath_shoes
'''

In [ ]:
category_counts=master_table['product_category_name'].value_counts()

In [ ]:
master_table['product_group']=np.where(master_table['product_category_name'].map(category_counts)<=1000,\
                                       'others',master_table['product_category_name'])

In [841]:
master_table['product_group'].value_counts()

product_group
others                      12333
Bed_Bath_Table              11982
Health_Beauty                9980
Sports_Leisure               8986
Furniture_Decor              8751
Computers_Accessories        8127
Housewares                   7368
Watches_Gifts                6208
Telephony                    4715
Garden_Tools                 4585
Auto                         4388
Toys                         4254
Cool_Stuff                   3991
Perfumery                    3553
Baby                         3190
Electronics                  2845
Stationery                   2625
Fashion_Bags_Accessories     2161
Pet_Shop                     2025
Office_Furniture             1782
Unknown                      1732
Consoles_Games               1182
Luggage_Accessories          1163
Name: count, dtype: int64

In [855]:
total_cat_prd_cnt=master_table.groupby(['customer_id','product_group']).agg\
                        (cat_prd_cnt=('product_id','count')).reset_index()

In [856]:
total_cat_prd_cnt.head(1)

                        customer_id product_group  cat_prd_cnt
0  00012a2ce6f8dcda20d059ce98491703          Toys            1

In [858]:
total_cat_prd_cnt=total_cat_prd_cnt.pivot_table(index='customer_id',columns='product_group',\
                                    values='cat_prd_cnt').reset_index()

In [859]:
total_cat_prd_cnt.fillna(0,inplace=True)

In [860]:
total_cat_prd_cnt.head()

product_group,customer_id,Auto,Baby,Bed_Bath_Table,Computers_Accessories,Consoles_Games,Cool_Stuff,Electronics,Fashion_Bags_Accessories,Furniture_Decor,...,Office_Furniture,Perfumery,Pet_Shop,Sports_Leisure,Stationery,Telephony,Toys,Unknown,Watches_Gifts,others
0,00012a2ce6f8dcda20d059ce98491703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,000161a058600d5901f007fab4c27140,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0001fd6190edaaf884bcaf3d49edf079,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0002414f95344307404f0ace7a26f1d5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,000379cdec625522490c315e70c7a9fb,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [862]:
new_col=[]
for i in total_cat_prd_cnt.columns:
    if i != 'customer_id':
        new_col.append('cat_prd_cnt_' + i)

In [863]:
['customer_id'] + new_col

['customer_id',
 'cat_prd_cnt_Auto',
 'cat_prd_cnt_Baby',
 'cat_prd_cnt_Bed_Bath_Table',
 'cat_prd_cnt_Computers_Accessories',
 'cat_prd_cnt_Consoles_Games',
 'cat_prd_cnt_Cool_Stuff',
 'cat_prd_cnt_Electronics',
 'cat_prd_cnt_Fashion_Bags_Accessories',
 'cat_prd_cnt_Furniture_Decor',
 'cat_prd_cnt_Garden_Tools',
 'cat_prd_cnt_Health_Beauty',
 'cat_prd_cnt_Housewares',
 'cat_prd_cnt_Luggage_Accessories',
 'cat_prd_cnt_Office_Furniture',
 'cat_prd_cnt_Perfumery',
 'cat_prd_cnt_Pet_Shop',
 'cat_prd_cnt_Sports_Leisure',
 'cat_prd_cnt_Stationery',
 'cat_prd_cnt_Telephony',
 'cat_prd_cnt_Toys',
 'cat_prd_cnt_Unknown',
 'cat_prd_cnt_Watches_Gifts',
 'cat_prd_cnt_others']

In [864]:
total_cat_prd_cnt.columns=['customer_id'] + new_col

In [865]:
total_cat_prd_cnt.head()

,customer_id,cat_prd_cnt_Auto,cat_prd_cnt_Baby,cat_prd_cnt_Bed_Bath_Table,cat_prd_cnt_Computers_Accessories,cat_prd_cnt_Consoles_Games,cat_prd_cnt_Cool_Stuff,cat_prd_cnt_Electronics,cat_prd_cnt_Fashion_Bags_Accessories,cat_prd_cnt_Furniture_Decor,...,cat_prd_cnt_Office_Furniture,cat_prd_cnt_Perfumery,cat_prd_cnt_Pet_Shop,cat_prd_cnt_Sports_Leisure,cat_prd_cnt_Stationery,cat_prd_cnt_Telephony,cat_prd_cnt_Toys,cat_prd_cnt_Unknown,cat_prd_cnt_Watches_Gifts,cat_prd_cnt_others
0,00012a2ce6f8dcda20d059ce98491703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,000161a058600d5901f007fab4c27140,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0001fd6190edaaf884bcaf3d49edf079,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0002414f95344307404f0ace7a26f1d5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,000379cdec625522490c315e70c7a9fb,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#total_cat_amt=
'''
cat_amt_Food
cat_amt_Kitchen_clean
cat_amt_Beauty
cat_amt_Imported_food
cat_amt_Drinks
cat_amt_Mother_child
cat_amt_Home
cat_amt_Nutrition
cat_amt_HH_Electrical
cat_amt_Office_sup_Comuters
cat_amt_Digital
cat_amt_Mobile
cat_amt_Car_prods
cat_amt_Cloath_shoes
'''

In [ ]:
#sale_price=total_amount
#sale_number=order_item_id
#sale_amount=payment_value

In [868]:
total_cnt_amt=master_table.groupby(['customer_id','product_group']).agg\
                        (cnt_amt=('payment_value','sum')).reset_index()

In [869]:
total_cnt_amt.head()

                        customer_id   product_group  cnt_amt
0  00012a2ce6f8dcda20d059ce98491703            Toys   114.74
1  000161a058600d5901f007fab4c27140   Health_Beauty    67.41
2  0001fd6190edaaf884bcaf3d49edf079            Baby   195.42
3  0002414f95344307404f0ace7a26f1d5      Cool_Stuff   179.35
4  000379cdec625522490c315e70c7a9fb  Bed_Bath_Table   107.01

In [870]:
total_cnt_amt=total_cnt_amt.pivot_table(index='customer_id',columns='product_group',
                          values='cnt_amt').reset_index()

In [871]:
new_col=[]
for i in total_cnt_amt.columns:
    if i != 'customer_id':
        new_col.append('cat_amt_' + i)

In [874]:
['customer_id'] + new_col

['customer_id',
 'cat_amt_Auto',
 'cat_amt_Baby',
 'cat_amt_Bed_Bath_Table',
 'cat_amt_Computers_Accessories',
 'cat_amt_Consoles_Games',
 'cat_amt_Cool_Stuff',
 'cat_amt_Electronics',
 'cat_amt_Fashion_Bags_Accessories',
 'cat_amt_Furniture_Decor',
 'cat_amt_Garden_Tools',
 'cat_amt_Health_Beauty',
 'cat_amt_Housewares',
 'cat_amt_Luggage_Accessories',
 'cat_amt_Office_Furniture',
 'cat_amt_Perfumery',
 'cat_amt_Pet_Shop',
 'cat_amt_Sports_Leisure',
 'cat_amt_Stationery',
 'cat_amt_Telephony',
 'cat_amt_Toys',
 'cat_amt_Unknown',
 'cat_amt_Watches_Gifts',
 'cat_amt_others']

In [875]:
total_cnt_amt.columns=['customer_id'] + new_col

In [878]:
total_cnt_amt.fillna(0,inplace=True)

In [879]:
total_cnt_amt.head(1)

,customer_id,cat_amt_Auto,cat_amt_Baby,cat_amt_Bed_Bath_Table,cat_amt_Computers_Accessories,cat_amt_Consoles_Games,cat_amt_Cool_Stuff,cat_amt_Electronics,cat_amt_Fashion_Bags_Accessories,cat_amt_Furniture_Decor,...,cat_amt_Office_Furniture,cat_amt_Perfumery,cat_amt_Pet_Shop,cat_amt_Sports_Leisure,cat_amt_Stationery,cat_amt_Telephony,cat_amt_Toys,cat_amt_Unknown,cat_amt_Watches_Gifts,cat_amt_others
0,00012a2ce6f8dcda20d059ce98491703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,114.74,0.0,0.0,0.0

In [ ]:
#total_cat_pen=
#cat_pen_cat = number of baskets ('trips') containing the category/number of baskets ('trips')

'''cat_pen_Food
cat_pen_Kitchen_clean
cat_pen_Beauty
cat_pen_Imported_food
cat_pen_Drinks
cat_pen_Mother_child
cat_pen_Home
cat_pen_Nutrition
cat_pen_HH_Electrical
cat_pen_Office_sup_Comuters
cat_pen_Digital
cat_pen_Mobile
cat_pen_Car_prods
cat_pen_Cloath_shoes
'''

In [885]:
total_cat_pen=master_table.groupby(['customer_id','product_group']).agg\
                        (cat_pen=('order_purchase_timestamp','nunique')).reset_index()

In [880]:
master_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'geolocation_zip_code_prefix',
       'geolocation_lat', 'geolocation_lng', 'geolocation_city',
       'geolocation_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value', 'review_id',
       'review_score', 'review_creation_date', 'review_answer_timestamp',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state', 'total_amount',
       'act_amt', 'cost_amt', 'margin', 'week_flag', 'promotion_flag',
       'discount', 'product_group'],
      dtype='object')

In [886]:
total_cat_pen.head(1)

                        customer_id product_group  cat_pen
0  00012a2ce6f8dcda20d059ce98491703          Toys        1

In [887]:
no_baskets.head()

                        customer_id  no_baskets
0  00012a2ce6f8dcda20d059ce98491703           1
1  000161a058600d5901f007fab4c27140           1
2  0001fd6190edaaf884bcaf3d49edf079           1
3  0002414f95344307404f0ace7a26f1d5           1
4  000379cdec625522490c315e70c7a9fb           1

In [888]:
total_cat_pen=total_cat_pen.merge(no_baskets,left_on='customer_id',right_on='customer_id',\
                                  how='left')

In [889]:
total_cat_pen.head()

                        customer_id   product_group  cat_pen  no_baskets
0  00012a2ce6f8dcda20d059ce98491703            Toys        1           1
1  000161a058600d5901f007fab4c27140   Health_Beauty        1           1
2  0001fd6190edaaf884bcaf3d49edf079            Baby        1           1
3  0002414f95344307404f0ace7a26f1d5      Cool_Stuff        1           1
4  000379cdec625522490c315e70c7a9fb  Bed_Bath_Table        1           1

In [890]:
total_cat_pen['penetration_value']=total_cat_pen['cat_pen']/total_cat_pen['no_baskets']

In [891]:
total_cat_pen.head()

,customer_id,product_group,cat_pen,no_baskets,penetration_value
0,00012a2ce6f8dcda20d059ce98491703,Toys,1,1,1.0
1,000161a058600d5901f007fab4c27140,Health_Beauty,1,1,1.0
2,0001fd6190edaaf884bcaf3d49edf079,Baby,1,1,1.0
3,0002414f95344307404f0ace7a26f1d5,Cool_Stuff,1,1,1.0
4,000379cdec625522490c315e70c7a9fb,Bed_Bath_Table,1,1,1.0

In [892]:
total_cat_pen=total_cat_pen.pivot_table(index='customer_id',columns='product_group',
                          values='penetration_value').reset_index()

In [893]:
total_cat_pen.head()

product_group,customer_id,Auto,Baby,Bed_Bath_Table,Computers_Accessories,Consoles_Games,Cool_Stuff,Electronics,Fashion_Bags_Accessories,Furniture_Decor,...,Office_Furniture,Perfumery,Pet_Shop,Sports_Leisure,Stationery,Telephony,Toys,Unknown,Watches_Gifts,others
0,00012a2ce6f8dcda20d059ce98491703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,000161a058600d5901f007fab4c27140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0001fd6190edaaf884bcaf3d49edf079,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0002414f95344307404f0ace7a26f1d5,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,000379cdec625522490c315e70c7a9fb,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [884]:
total_cat_pen.head(1)

product_group,customer_id,Auto,Baby,Bed_Bath_Table,Computers_Accessories,Consoles_Games,Cool_Stuff,Electronics,Fashion_Bags_Accessories,Furniture_Decor,...,Office_Furniture,Perfumery,Pet_Shop,Sports_Leisure,Stationery,Telephony,Toys,Unknown,Watches_Gifts,others
0,00012a2ce6f8dcda20d059ce98491703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN

In [894]:
total_cat_pen.fillna(0,inplace=True)

In [895]:
new_col=[]
for i in total_cat_pen.columns:
    if i != 'customer_id':
        new_col.append('cat_pen_' + i)

In [897]:
['customer_id']+new_col

['customer_id',
 'cat_pen_Auto',
 'cat_pen_Baby',
 'cat_pen_Bed_Bath_Table',
 'cat_pen_Computers_Accessories',
 'cat_pen_Consoles_Games',
 'cat_pen_Cool_Stuff',
 'cat_pen_Electronics',
 'cat_pen_Fashion_Bags_Accessories',
 'cat_pen_Furniture_Decor',
 'cat_pen_Garden_Tools',
 'cat_pen_Health_Beauty',
 'cat_pen_Housewares',
 'cat_pen_Luggage_Accessories',
 'cat_pen_Office_Furniture',
 'cat_pen_Perfumery',
 'cat_pen_Pet_Shop',
 'cat_pen_Sports_Leisure',
 'cat_pen_Stationery',
 'cat_pen_Telephony',
 'cat_pen_Toys',
 'cat_pen_Unknown',
 'cat_pen_Watches_Gifts',
 'cat_pen_others']

In [898]:
total_cat_pen.columns=['customer_id']+new_col

In [899]:
total_cat_pen.head(1)

,customer_id,cat_pen_Auto,cat_pen_Baby,cat_pen_Bed_Bath_Table,cat_pen_Computers_Accessories,cat_pen_Consoles_Games,cat_pen_Cool_Stuff,cat_pen_Electronics,cat_pen_Fashion_Bags_Accessories,cat_pen_Furniture_Decor,...,cat_pen_Office_Furniture,cat_pen_Perfumery,cat_pen_Pet_Shop,cat_pen_Sports_Leisure,cat_pen_Stationery,cat_pen_Telephony,cat_pen_Toys,cat_pen_Unknown,cat_pen_Watches_Gifts,cat_pen_others
0,00012a2ce6f8dcda20d059ce98491703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [ ]:
#total_cat_pur=purchase Flag in this category (Purchasing atleast one product from this category)
'''
cat_pur_Food
cat_pur_Kitchen_clean
cat_pur_Beauty
cat_pur_Imported_food
cat_pur_Drinks
cat_pur_Mother_child
cat_pur_Home
cat_pur_Nutrition
cat_pur_HH_Electrical
cat_pur_Office_sup_Comuters
cat_pur_Digital
cat_pur_Mobile
cat_pur_Car_prods
cat_pur_Cloath_shoes
'''

In [923]:
total_cat_pur=master_table.groupby(['customer_id','product_group']).agg\
                        (cat_pur=('product_group','count')).reset_index()

In [924]:
total_cat_pur=total_cat_pur.pivot_table(index='customer_id',columns='product_group',
                                        values='cat_pur').reset_index()

In [925]:
total_cat_pur.fillna(0,inplace=True)

In [926]:
total_cat_pur.head(1)

product_group,customer_id,Auto,Baby,Bed_Bath_Table,Computers_Accessories,Consoles_Games,Cool_Stuff,Electronics,Fashion_Bags_Accessories,Furniture_Decor,...,Office_Furniture,Perfumery,Pet_Shop,Sports_Leisure,Stationery,Telephony,Toys,Unknown,Watches_Gifts,others
0,00012a2ce6f8dcda20d059ce98491703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [927]:
new_col=[]
for i in total_cat_pur.columns:
    if i != 'customer_id':
        new_col.append('cat_pur_' + i)

In [928]:
['customer_id'] + new_col

['customer_id',
 'cat_pur_Auto',
 'cat_pur_Baby',
 'cat_pur_Bed_Bath_Table',
 'cat_pur_Computers_Accessories',
 'cat_pur_Consoles_Games',
 'cat_pur_Cool_Stuff',
 'cat_pur_Electronics',
 'cat_pur_Fashion_Bags_Accessories',
 'cat_pur_Furniture_Decor',
 'cat_pur_Garden_Tools',
 'cat_pur_Health_Beauty',
 'cat_pur_Housewares',
 'cat_pur_Luggage_Accessories',
 'cat_pur_Office_Furniture',
 'cat_pur_Perfumery',
 'cat_pur_Pet_Shop',
 'cat_pur_Sports_Leisure',
 'cat_pur_Stationery',
 'cat_pur_Telephony',
 'cat_pur_Toys',
 'cat_pur_Unknown',
 'cat_pur_Watches_Gifts',
 'cat_pur_others']

In [929]:
total_cat_pur.columns=['customer_id'] + new_col

In [930]:
total_cat_pur[new_col].applymap(lambda x : 1 if x>0 else 0)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\3383281305.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  total_cat_pur[new_col].applymap(lambda x : 1 if x>0 else 0)

,cat_pur_Auto,cat_pur_Baby,cat_pur_Bed_Bath_Table,cat_pur_Computers_Accessories,cat_pur_Consoles_Games,cat_pur_Cool_Stuff,cat_pur_Electronics,cat_pur_Fashion_Bags_Accessories,cat_pur_Furniture_Decor,cat_pur_Garden_Tools,...,cat_pur_Office_Furniture,cat_pur_Perfumery,cat_pur_Pet_Shop,cat_pur_Sports_Leisure,cat_pur_Stationery,cat_pur_Telephony,cat_pur_Toys,cat_pur_Unknown,cat_pur_Watches_Gifts,cat_pur_others
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98350,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
98351,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98352,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
98353,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98354,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [938]:
total_cat_pur=pd.concat((total_cat_pur['customer_id'],\
           total_cat_pur[new_col].applymap(lambda x : 1 if x>0 else 0)),axis=1)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\1191342714.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  total_cat_pur[new_col].applymap(lambda x : 1 if x>0 else 0)),axis=1)

In [939]:
total_cat_pur.head()

,customer_id,cat_pur_Auto,cat_pur_Baby,cat_pur_Bed_Bath_Table,cat_pur_Computers_Accessories,cat_pur_Consoles_Games,cat_pur_Cool_Stuff,cat_pur_Electronics,cat_pur_Fashion_Bags_Accessories,cat_pur_Furniture_Decor,...,cat_pur_Office_Furniture,cat_pur_Perfumery,cat_pur_Pet_Shop,cat_pur_Sports_Leisure,cat_pur_Stationery,cat_pur_Telephony,cat_pur_Toys,cat_pur_Unknown,cat_pur_Watches_Gifts,cat_pur_others
0,00012a2ce6f8dcda20d059ce98491703,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,000161a058600d5901f007fab4c27140,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0001fd6190edaaf884bcaf3d49edf079,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0002414f95344307404f0ace7a26f1d5,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,000379cdec625522490c315e70c7a9fb,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#total_cat_first=First purchase Flag in this category
#                (Purchasing atleast one product from this category)

'''
cat_first_Food
cat_first_Kitchen_clean
cat_first_Beauty
cat_first_Imported_food
cat_first_Drinks
cat_first_Mother_child
cat_first_Home
cat_first_Nutrition
cat_first_HH_Electrical
cat_first_Office_sup_Comuters
cat_first_Digital
cat_first_Mobile
cat_first_Car_prods
cat_first_Cloath_shoes
No_Distinct_categories
cat_cnt_first_purchase
'''

In [944]:
master_table['first_purchase_flag']=np.where(master_table['order_purchase_timestamp']==\
                                            master_table['order_purchase_timestamp'].min(),1,0)

In [945]:
master_table['first_purchase_flag'].value_counts()

first_purchase_flag
0    118741
1         1
Name: count, dtype: int64

In [946]:
master_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'geolocation_zip_code_prefix',
       'geolocation_lat', 'geolocation_lng', 'geolocation_city',
       'geolocation_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value', 'review_id',
       'review_score', 'review_creation_date', 'review_answer_timestamp',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state', 'total_amount',
       'act_amt', 'cost_amt', 'margin', 'week_flag', 'promotion_flag',
       'discount', 'product_group', 'first_purchase_flag'],
      dtype='object')

In [947]:
first_purchase_flag_count=master_table.loc[master_table['first_purchase_flag']==1]

In [948]:
first_purchase_flag_count

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_timestamp_period_flag,customer_zip_code_prefix,...,seller_state,total_amount,act_amt,cost_amt,margin,week_flag,promotion_flag,discount,product_group,first_purchase_flag
47518,bd50a7fe9fd97ea4b7663031a319e150,0975c3cf2e418ebfa5d1191a2dffd59d,delivered,2016-12-23,2016-12-23,2016-12-27,2016-12-28,2017-01-19,P1,80030,...,Andhra Pradesh,19.62,19.62,19.62,0.0,weekday,promotion,0.0,Fashion_Bags_Accessories,1

In [949]:
total_cat_first=master_table.groupby(['customer_id','product_group']).agg\
                        (cat_first=('product_group','count')).reset_index()

In [950]:
total_cat_first=total_cat_first.pivot_table(index='customer_id',columns='product_group',
                                        values='cat_first').reset_index()

In [952]:
total_cat_first.fillna(0,inplace=True)

In [953]:
total_cat_first.head()

product_group,customer_id,Auto,Baby,Bed_Bath_Table,Computers_Accessories,Consoles_Games,Cool_Stuff,Electronics,Fashion_Bags_Accessories,Furniture_Decor,...,Office_Furniture,Perfumery,Pet_Shop,Sports_Leisure,Stationery,Telephony,Toys,Unknown,Watches_Gifts,others
0,00012a2ce6f8dcda20d059ce98491703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,000161a058600d5901f007fab4c27140,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0001fd6190edaaf884bcaf3d49edf079,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0002414f95344307404f0ace7a26f1d5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,000379cdec625522490c315e70c7a9fb,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [954]:
new_col=[]
for i in total_cat_pur.columns:
    if i != 'customer_id':
        new_col.append('cat_pur_' + i)

In [955]:
['customer_id'] + new_col

['customer_id',
 'cat_pur_cat_pur_Auto',
 'cat_pur_cat_pur_Baby',
 'cat_pur_cat_pur_Bed_Bath_Table',
 'cat_pur_cat_pur_Computers_Accessories',
 'cat_pur_cat_pur_Consoles_Games',
 'cat_pur_cat_pur_Cool_Stuff',
 'cat_pur_cat_pur_Electronics',
 'cat_pur_cat_pur_Fashion_Bags_Accessories',
 'cat_pur_cat_pur_Furniture_Decor',
 'cat_pur_cat_pur_Garden_Tools',
 'cat_pur_cat_pur_Health_Beauty',
 'cat_pur_cat_pur_Housewares',
 'cat_pur_cat_pur_Luggage_Accessories',
 'cat_pur_cat_pur_Office_Furniture',
 'cat_pur_cat_pur_Perfumery',
 'cat_pur_cat_pur_Pet_Shop',
 'cat_pur_cat_pur_Sports_Leisure',
 'cat_pur_cat_pur_Stationery',
 'cat_pur_cat_pur_Telephony',
 'cat_pur_cat_pur_Toys',
 'cat_pur_cat_pur_Unknown',
 'cat_pur_cat_pur_Watches_Gifts',
 'cat_pur_cat_pur_others']

In [956]:
total_cat_first.columns=['customer_id'] + new_col

In [957]:
total_cat_first.head()

,customer_id,cat_pur_cat_pur_Auto,cat_pur_cat_pur_Baby,cat_pur_cat_pur_Bed_Bath_Table,cat_pur_cat_pur_Computers_Accessories,cat_pur_cat_pur_Consoles_Games,cat_pur_cat_pur_Cool_Stuff,cat_pur_cat_pur_Electronics,cat_pur_cat_pur_Fashion_Bags_Accessories,cat_pur_cat_pur_Furniture_Decor,...,cat_pur_cat_pur_Office_Furniture,cat_pur_cat_pur_Perfumery,cat_pur_cat_pur_Pet_Shop,cat_pur_cat_pur_Sports_Leisure,cat_pur_cat_pur_Stationery,cat_pur_cat_pur_Telephony,cat_pur_cat_pur_Toys,cat_pur_cat_pur_Unknown,cat_pur_cat_pur_Watches_Gifts,cat_pur_cat_pur_others
0,00012a2ce6f8dcda20d059ce98491703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,000161a058600d5901f007fab4c27140,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0001fd6190edaaf884bcaf3d49edf079,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0002414f95344307404f0ace7a26f1d5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,000379cdec625522490c315e70c7a9fb,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [959]:
total_cat_first[new_col].applymap(lambda x : 1 if x>0 else 0)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\1739301781.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  total_cat_first[new_col].applymap(lambda x : 1 if x>0 else 0)

,cat_pur_cat_pur_Auto,cat_pur_cat_pur_Baby,cat_pur_cat_pur_Bed_Bath_Table,cat_pur_cat_pur_Computers_Accessories,cat_pur_cat_pur_Consoles_Games,cat_pur_cat_pur_Cool_Stuff,cat_pur_cat_pur_Electronics,cat_pur_cat_pur_Fashion_Bags_Accessories,cat_pur_cat_pur_Furniture_Decor,cat_pur_cat_pur_Garden_Tools,...,cat_pur_cat_pur_Office_Furniture,cat_pur_cat_pur_Perfumery,cat_pur_cat_pur_Pet_Shop,cat_pur_cat_pur_Sports_Leisure,cat_pur_cat_pur_Stationery,cat_pur_cat_pur_Telephony,cat_pur_cat_pur_Toys,cat_pur_cat_pur_Unknown,cat_pur_cat_pur_Watches_Gifts,cat_pur_cat_pur_others
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98350,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
98351,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98352,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
98353,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98354,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [961]:
total_cat_first=pd.concat((total_cat_first['customer_id'],
                   total_cat_first[new_col].applymap(lambda x : 1 if x>0 else 0)),axis=1)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\4151344422.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  total_cat_first[new_col].applymap(lambda x : 1 if x>0 else 0)),axis=1)

In [963]:
total_cat_first.head()

,customer_id,cat_pur_cat_pur_Auto,cat_pur_cat_pur_Baby,cat_pur_cat_pur_Bed_Bath_Table,cat_pur_cat_pur_Computers_Accessories,cat_pur_cat_pur_Consoles_Games,cat_pur_cat_pur_Cool_Stuff,cat_pur_cat_pur_Electronics,cat_pur_cat_pur_Fashion_Bags_Accessories,cat_pur_cat_pur_Furniture_Decor,...,cat_pur_cat_pur_Office_Furniture,cat_pur_cat_pur_Perfumery,cat_pur_cat_pur_Pet_Shop,cat_pur_cat_pur_Sports_Leisure,cat_pur_cat_pur_Stationery,cat_pur_cat_pur_Telephony,cat_pur_cat_pur_Toys,cat_pur_cat_pur_Unknown,cat_pur_cat_pur_Watches_Gifts,cat_pur_cat_pur_others
0,00012a2ce6f8dcda20d059ce98491703,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,000161a058600d5901f007fab4c27140,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0001fd6190edaaf884bcaf3d49edf079,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0002414f95344307404f0ace7a26f1d5,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,000379cdec625522490c315e70c7a9fb,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#No_Distinct_categories=How many distinct categories purchased from all categories?

In [964]:
no_Distinct_categories=master_table.groupby(['customer_id']).agg\
                        (no_Distinct_categories=('product_group','nunique')).reset_index()

In [965]:
no_Distinct_categories.head(1)

                        customer_id  no_Distinct_categories
0  00012a2ce6f8dcda20d059ce98491703                       1

In [ ]:
#cat_cnt_first_purchase=How many distinct categories purchased in the first basket purchase

In [966]:
first_purchase_flag_count.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_timestamp_period_flag,customer_zip_code_prefix,...,seller_state,total_amount,act_amt,cost_amt,margin,week_flag,promotion_flag,discount,product_group,first_purchase_flag
47518,bd50a7fe9fd97ea4b7663031a319e150,0975c3cf2e418ebfa5d1191a2dffd59d,delivered,2016-12-23,2016-12-23,2016-12-27,2016-12-28,2017-01-19,P1,80030,...,Andhra Pradesh,19.62,19.62,19.62,0.0,weekday,promotion,0.0,Fashion_Bags_Accessories,1

In [967]:
cat_cnt_first_purchase=first_purchase_flag_count.groupby(['customer_id']).agg\
                        (cat_cnt_first_purchase=('product_group','nunique')).reset_index()

In [968]:
cat_cnt_first_purchase.head()

                        customer_id  cat_cnt_first_purchase
0  0975c3cf2e418ebfa5d1191a2dffd59d                       1

In [ ]:
#merge all the aggregated tables with the customer table with Customer_ID
#list of all aggregated tables
'''
no_baskets
sale_amount
sale_amount_p1
sale_amount_p2
no_baskets_weekend
no_baskets_w_promo_prds
quantiy
discount_items
no_prds
no_prds_weekend
no_prds_promo
total_cat_prd_cnt
total_cnt_amt
total_cat_pen
total_cat_pur
total_cat_first
No_Distinct_categories
cat_cnt_first_purchase
'''

In [1153]:
clean_table=\
    master_table.merge(no_baskets,left_on='customer_id',right_on='customer_id',how='left').merge\
                (sale_amount,left_on='customer_id',right_on='customer_id',how='left').merge\
                (sale_amount_p1,left_on='customer_id',right_on='customer_id',how='left').merge\
                (sale_amount_p2,left_on='customer_id',right_on='customer_id',how='left').merge\
                (no_baskets_weekend,left_on='customer_id',right_on='customer_id',how='left').merge\
                (no_baskets_w_promo_prds,left_on='customer_id',right_on='customer_id',how='left').merge\
                (quantity,left_on='customer_id',right_on='customer_id',how='left').merge\
                (discount_item,left_on='customer_id',right_on='customer_id',how='left').merge\
                (no_prds,left_on='customer_id',right_on='customer_id',how='left').merge\
                (no_prds_weekend,left_on='customer_id',right_on='customer_id',how='left').merge\
                (no_prds_promo,left_on='customer_id',right_on='customer_id',how='left').merge\
                (total_cat_prd_cnt,left_on='customer_id',right_on='customer_id',how='left').merge\
                (total_cnt_amt,left_on='customer_id',right_on='customer_id',how='left').merge\
                (total_cat_pen,left_on='customer_id',right_on='customer_id',how='left').merge\
                (total_cat_pur,left_on='customer_id',right_on='customer_id',how='left').merge\
                (total_cat_first,left_on='customer_id',right_on='customer_id',how='left').merge\
                (no_Distinct_categories,left_on='customer_id',right_on='customer_id',how='left').merge\
                (cat_cnt_first_purchase,left_on='customer_id',right_on='customer_id',how='left').merge\
                (total_act_amount,left_on='customer_id',right_on='customer_id',how='left')

In [1154]:
clean_table.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_timestamp_period_flag,customer_zip_code_prefix,...,cat_pur_cat_pur_Sports_Leisure,cat_pur_cat_pur_Stationery,cat_pur_cat_pur_Telephony,cat_pur_cat_pur_Toys,cat_pur_cat_pur_Unknown,cat_pur_cat_pur_Watches_Gifts,cat_pur_cat_pur_others,no_Distinct_categories,cat_cnt_first_purchase,total_act_amount
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,P1,3149,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,NaN,116.13
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,P1,3149,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,NaN,116.13
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,P1,3149,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,NaN,116.13
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24,2018-07-26,2018-07-26,2018-08-07,2018-08-13,P2,47813,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,NaN,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08,2018-08-08,2018-08-08,2018-08-17,2018-09-04,P2,75265,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,NaN,179.12

In [1155]:
print(f'{clean_table.columns}')

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       ...
       'cat_pur_cat_pur_Sports_Leisure', 'cat_pur_cat_pur_Stationery',
       'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys',
       'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts',
       'cat_pur_cat_pur_others', 'no_Distinct_categories',
       'cat_cnt_first_purchase', 'total_act_amount'],
      dtype='object', length=180)

In [1156]:
clean_table=clean_table.drop(columns=['customer_city','customer_state','geolocation_lat',
                                'geolocation_lng','geolocation_city',
                                'geolocation_state','shipping_limit_date',
                                'payment_type','review_id',
                                'review_creation_date','review_answer_timestamp',
                                'product_name_lenght','product_description_lenght',
                                'product_photos_qty','product_weight_g','product_length_cm',
                                'product_height_cm','product_width_cm','seller_city','seller_state'
                               ])

In [1157]:
clean_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       ...
       'cat_pur_cat_pur_Sports_Leisure', 'cat_pur_cat_pur_Stationery',
       'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys',
       'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts',
       'cat_pur_cat_pur_others', 'no_Distinct_categories',
       'cat_cnt_first_purchase', 'total_act_amount'],
      dtype='object', length=160)

In [1158]:
clean_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118742 entries, 0 to 118741
Columns: 160 entries, order_id to total_act_amount
dtypes: datetime64[ns](5), float64(135), int64(10), object(10)
memory usage: 144.9+ MB

In [1159]:
clean_table.fillna(0,inplace=True)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14840\897729363.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  clean_table.fillna(0,inplace=True)

In [1160]:
clean_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       ...
       'cat_pur_cat_pur_Sports_Leisure', 'cat_pur_cat_pur_Stationery',
       'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys',
       'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts',
       'cat_pur_cat_pur_others', 'no_Distinct_categories',
       'cat_cnt_first_purchase', 'total_act_amount'],
      dtype='object', length=160)

In [1161]:
clean_table.columns[clean_table.isnull().sum()>0]

Index([], dtype='object')

In [1162]:
#avg_basket_value=Sum(sale_amount)/No.of baskets

In [1163]:
clean_table['avg_basket_value']= clean_table['sale_amount']/clean_table['no_baskets']

In [1164]:
clean_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       ...
       'cat_pur_cat_pur_Stationery', 'cat_pur_cat_pur_Telephony',
       'cat_pur_cat_pur_Toys', 'cat_pur_cat_pur_Unknown',
       'cat_pur_cat_pur_Watches_Gifts', 'cat_pur_cat_pur_others',
       'no_Distinct_categories', 'cat_cnt_first_purchase', 'total_act_amount',
       'avg_basket_value'],
      dtype='object', length=161)

In [1165]:
#avg_margin=margin/no.of baskets

In [1166]:
clean_table['avg_margin']=clean_table['margin']/clean_table['no_baskets']

In [1167]:
clean_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       ...
       'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys',
       'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts',
       'cat_pur_cat_pur_others', 'no_Distinct_categories',
       'cat_cnt_first_purchase', 'total_act_amount', 'avg_basket_value',
       'avg_margin'],
      dtype='object', length=162)

In [1168]:
#avg_quantiy=sum(sale_number)/no.of baskets

In [1169]:
clean_table['avg_quantity']=clean_table['sale_amount']/clean_table['no_baskets']

In [1170]:
clean_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       ...
       'cat_pur_cat_pur_Toys', 'cat_pur_cat_pur_Unknown',
       'cat_pur_cat_pur_Watches_Gifts', 'cat_pur_cat_pur_others',
       'no_Distinct_categories', 'cat_cnt_first_purchase', 'total_act_amount',
       'avg_basket_value', 'avg_margin', 'avg_quantity'],
      dtype='object', length=163)

In [1171]:
#avg_discount=discount/no.of baskets

In [1172]:
clean_table['avg_discount']=clean_table['discount']/clean_table['no_baskets']

In [1173]:
clean_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       ...
       'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts',
       'cat_pur_cat_pur_others', 'no_Distinct_categories',
       'cat_cnt_first_purchase', 'total_act_amount', 'avg_basket_value',
       'avg_margin', 'avg_quantity', 'avg_discount'],
      dtype='object', length=164)

In [1174]:
#Avg_no_prds=no_prds/no.of baskets

In [1175]:
clean_table['avg_no_prds']=clean_table['no_prods']/clean_table['no_baskets']

In [1176]:
clean_table.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix',
       ...
       'cat_pur_cat_pur_Watches_Gifts', 'cat_pur_cat_pur_others',
       'no_Distinct_categories', 'cat_cnt_first_purchase', 'total_act_amount',
       'avg_basket_value', 'avg_margin', 'avg_quantity', 'avg_discount',
       'avg_no_prds'],
      dtype='object', length=165)

In [1177]:
clean_table.fillna(0,inplace=True)

In [1178]:
#buyer_flag=One time buyer/Repeat buyer	
#-----------if no_baskets = 1 then buyer_flag = "One_time Buyer"; else buyer_flag = "Repeat Buyer";
active_buyers=clean_table.loc[clean_table['no_baskets'] != 0]

In [1179]:
active_buyers['buyer_flag']=np.where(active_buyers['no_baskets']==1,'one_time_Buyer','repeat_Buyer')

In [1180]:
#review_flag=Customer who reviewed for product
#-------------if reviews > 0 then redeem_flag = 1; else redeem_flag = 0;

In [1181]:
active_buyers['review_flag']=np.where(active_buyers['review_score']>0,1,0)

In [1182]:
active_buyers['review_flag'].value_counts()

review_flag
1    118742
Name: count, dtype: int64

In [1183]:
#multi_cat_flag=one category purchased/multi category purchased	
#----------------if cat_cnt =1 then multi_cat_flag = 0; else multi_cat_flag = 1;

In [1184]:
active_buyers['multi_cat_flag']=np.where(active_buyers['no_Distinct_categories']==1,0,1)

In [1185]:
active_buyers['multi_cat_flag'].value_counts()

multi_cat_flag
0    115843
1      2899
Name: count, dtype: int64

In [1186]:
#margin_pct=Percentage of margin	
#-----------if sale_amount = 0 then margin_pct=.; else margin_pct = margin/sale_amount

In [1187]:
active_buyers['margin_pct']=np.where(active_buyers['sale_amount']==0,0,
                                   active_buyers['margin']/active_buyers['sale_amount'])

In [1188]:
active_buyers['margin_pct']

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
118737    0.0
118738    0.0
118739    0.0
118740   -0.5
118741    0.0
Name: margin_pct, Length: 118742, dtype: float64

In [1189]:
print(f'{active_buyers.columns.to_list()}')

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix', 'geolocation_zip_code_prefix', 'order_item_id', 'product_id', 'seller_id', 'price', 'freight_value', 'payment_sequential', 'payment_installments', 'payment_value', 'review_score', 'product_category_name', 'seller_zip_code_prefix', 'total_amount', 'act_amt', 'cost_amt', 'margin', 'week_flag', 'promotion_flag', 'discount', 'product_group', 'first_purchase_flag', 'no_baskets', 'sale_amount', 'sale_amount_p1', 'sale_amount_p2', 'no_baskets_weekend', 'no_baskets_w_promo_prds', 'quantity', 'discount_item', 'no_prods', 'no_prds_weekend', 'no_prds_promo', 'cat_prd_cnt_Auto', 'cat_prd_cnt_Baby', 'cat_prd_cnt_Bed_Bath_Table', 'cat_prd_cnt_Computers_Accessories', 'cat_prd_cnt_Consoles_Games', 'cat_prd_cnt_Cool_Stuff', 'cat_prd_cnt_Electronics', 'cat_prd_cnt_Fashion_Bags_Accessories', 'cat_prd_cnt_Furniture_Decor', 'cat_prd_cnt_Garden_Tools', 'cat_prd_cnt_Health_Beauty', 'cat_prd_cnt_Housewares', 'cat_prd_cnt_Luggage_Accessories', 'cat_prd_cnt_Office_Furniture', 'cat_prd_cnt_Perfumery', 'cat_prd_cnt_Pet_Shop', 'cat_prd_cnt_Sports_Leisure', 'cat_prd_cnt_Stationery', 'cat_prd_cnt_Telephony', 'cat_prd_cnt_Toys', 'cat_prd_cnt_Unknown', 'cat_prd_cnt_Watches_Gifts', 'cat_prd_cnt_others', 'cat_amt_Auto', 'cat_amt_Baby', 'cat_amt_Bed_Bath_Table', 'cat_amt_Computers_Accessories', 'cat_amt_Consoles_Games', 'cat_amt_Cool_Stuff', 'cat_amt_Electronics', 'cat_amt_Fashion_Bags_Accessories', 'cat_amt_Furniture_Decor', 'cat_amt_Garden_Tools', 'cat_amt_Health_Beauty', 'cat_amt_Housewares', 'cat_amt_Luggage_Accessories', 'cat_amt_Office_Furniture', 'cat_amt_Perfumery', 'cat_amt_Pet_Shop', 'cat_amt_Sports_Leisure', 'cat_amt_Stationery', 'cat_amt_Telephony', 'cat_amt_Toys', 'cat_amt_Unknown', 'cat_amt_Watches_Gifts', 'cat_amt_others', 'cat_pen_Auto', 'cat_pen_Baby', 'cat_pen_Bed_Bath_Table', 'cat_pen_Computers_Accessories', 'cat_pen_Consoles_Games', 'cat_pen_Cool_Stuff', 'cat_pen_Electronics', 'cat_pen_Fashion_Bags_Accessories', 'cat_pen_Furniture_Decor', 'cat_pen_Garden_Tools', 'cat_pen_Health_Beauty', 'cat_pen_Housewares', 'cat_pen_Luggage_Accessories', 'cat_pen_Office_Furniture', 'cat_pen_Perfumery', 'cat_pen_Pet_Shop', 'cat_pen_Sports_Leisure', 'cat_pen_Stationery', 'cat_pen_Telephony', 'cat_pen_Toys', 'cat_pen_Unknown', 'cat_pen_Watches_Gifts', 'cat_pen_others', 'cat_pur_Auto', 'cat_pur_Baby', 'cat_pur_Bed_Bath_Table', 'cat_pur_Computers_Accessories', 'cat_pur_Consoles_Games', 'cat_pur_Cool_Stuff', 'cat_pur_Electronics', 'cat_pur_Fashion_Bags_Accessories', 'cat_pur_Furniture_Decor', 'cat_pur_Garden_Tools', 'cat_pur_Health_Beauty', 'cat_pur_Housewares', 'cat_pur_Luggage_Accessories', 'cat_pur_Office_Furniture', 'cat_pur_Perfumery', 'cat_pur_Pet_Shop', 'cat_pur_Sports_Leisure', 'cat_pur_Stationery', 'cat_pur_Telephony', 'cat_pur_Toys', 'cat_pur_Unknown', 'cat_pur_Watches_Gifts', 'cat_pur_others', 'cat_pur_cat_pur_Auto', 'cat_pur_cat_pur_Baby', 'cat_pur_cat_pur_Bed_Bath_Table', 'cat_pur_cat_pur_Computers_Accessories', 'cat_pur_cat_pur_Consoles_Games', 'cat_pur_cat_pur_Cool_Stuff', 'cat_pur_cat_pur_Electronics', 'cat_pur_cat_pur_Fashion_Bags_Accessories', 'cat_pur_cat_pur_Furniture_Decor', 'cat_pur_cat_pur_Garden_Tools', 'cat_pur_cat_pur_Health_Beauty', 'cat_pur_cat_pur_Housewares', 'cat_pur_cat_pur_Luggage_Accessories', 'cat_pur_cat_pur_Office_Furniture', 'cat_pur_cat_pur_Perfumery', 'cat_pur_cat_pur_Pet_Shop', 'cat_pur_cat_pur_Sports_Leisure', 'cat_pur_cat_pur_Stationery', 'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys', 'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts', 'cat_pur_cat_pur_others', 'no_Distinct_categories', 'cat_cnt_first_purchase', 'total_act_amount', 'avg_basket_value', 'avg_margin', 'avg_quantity', 'avg_discount', 'avg_no_prds', 'buyer_flag', 'review_flag', 'multi_cat_flag', 'margin_pct']

In [1190]:
#discount_pct=Percentage of discount	
#--------------if act_amt = 0 then discount_pct=.; else discount_pct = discount/act_amt;

In [1191]:
total_act_amount=master_table.groupby(['customer_id']).agg\
                    (total_act_amount=('act_amt','sum')).reset_index().fillna(0)

In [1192]:
#now merge it into master_table and rerun all the syntax

In [1193]:
active_buyers['discount_pct']=np.where(active_buyers['act_amt']==0,0, 
                                       active_buyers['discount']/active_buyers['total_act_amount'])

In [1194]:
print(f'{active_buyers.columns.to_list()}')

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix', 'geolocation_zip_code_prefix', 'order_item_id', 'product_id', 'seller_id', 'price', 'freight_value', 'payment_sequential', 'payment_installments', 'payment_value', 'review_score', 'product_category_name', 'seller_zip_code_prefix', 'total_amount', 'act_amt', 'cost_amt', 'margin', 'week_flag', 'promotion_flag', 'discount', 'product_group', 'first_purchase_flag', 'no_baskets', 'sale_amount', 'sale_amount_p1', 'sale_amount_p2', 'no_baskets_weekend', 'no_baskets_w_promo_prds', 'quantity', 'discount_item', 'no_prods', 'no_prds_weekend', 'no_prds_promo', 'cat_prd_cnt_Auto', 'cat_prd_cnt_Baby', 'cat_prd_cnt_Bed_Bath_Table', 'cat_prd_cnt_Computers_Accessories', 'cat_prd_cnt_Consoles_Games', 'cat_prd_cnt_Cool_Stuff', 'cat_prd_cnt_Electronics', 'cat_prd_cnt_Fashion_Bags_Accessories', 'cat_prd_cnt_Furniture_Decor', 'cat_prd_cnt_Garden_Tools', 'cat_prd_cnt_Health_Beauty', 'cat_prd_cnt_Housewares', 'cat_prd_cnt_Luggage_Accessories', 'cat_prd_cnt_Office_Furniture', 'cat_prd_cnt_Perfumery', 'cat_prd_cnt_Pet_Shop', 'cat_prd_cnt_Sports_Leisure', 'cat_prd_cnt_Stationery', 'cat_prd_cnt_Telephony', 'cat_prd_cnt_Toys', 'cat_prd_cnt_Unknown', 'cat_prd_cnt_Watches_Gifts', 'cat_prd_cnt_others', 'cat_amt_Auto', 'cat_amt_Baby', 'cat_amt_Bed_Bath_Table', 'cat_amt_Computers_Accessories', 'cat_amt_Consoles_Games', 'cat_amt_Cool_Stuff', 'cat_amt_Electronics', 'cat_amt_Fashion_Bags_Accessories', 'cat_amt_Furniture_Decor', 'cat_amt_Garden_Tools', 'cat_amt_Health_Beauty', 'cat_amt_Housewares', 'cat_amt_Luggage_Accessories', 'cat_amt_Office_Furniture', 'cat_amt_Perfumery', 'cat_amt_Pet_Shop', 'cat_amt_Sports_Leisure', 'cat_amt_Stationery', 'cat_amt_Telephony', 'cat_amt_Toys', 'cat_amt_Unknown', 'cat_amt_Watches_Gifts', 'cat_amt_others', 'cat_pen_Auto', 'cat_pen_Baby', 'cat_pen_Bed_Bath_Table', 'cat_pen_Computers_Accessories', 'cat_pen_Consoles_Games', 'cat_pen_Cool_Stuff', 'cat_pen_Electronics', 'cat_pen_Fashion_Bags_Accessories', 'cat_pen_Furniture_Decor', 'cat_pen_Garden_Tools', 'cat_pen_Health_Beauty', 'cat_pen_Housewares', 'cat_pen_Luggage_Accessories', 'cat_pen_Office_Furniture', 'cat_pen_Perfumery', 'cat_pen_Pet_Shop', 'cat_pen_Sports_Leisure', 'cat_pen_Stationery', 'cat_pen_Telephony', 'cat_pen_Toys', 'cat_pen_Unknown', 'cat_pen_Watches_Gifts', 'cat_pen_others', 'cat_pur_Auto', 'cat_pur_Baby', 'cat_pur_Bed_Bath_Table', 'cat_pur_Computers_Accessories', 'cat_pur_Consoles_Games', 'cat_pur_Cool_Stuff', 'cat_pur_Electronics', 'cat_pur_Fashion_Bags_Accessories', 'cat_pur_Furniture_Decor', 'cat_pur_Garden_Tools', 'cat_pur_Health_Beauty', 'cat_pur_Housewares', 'cat_pur_Luggage_Accessories', 'cat_pur_Office_Furniture', 'cat_pur_Perfumery', 'cat_pur_Pet_Shop', 'cat_pur_Sports_Leisure', 'cat_pur_Stationery', 'cat_pur_Telephony', 'cat_pur_Toys', 'cat_pur_Unknown', 'cat_pur_Watches_Gifts', 'cat_pur_others', 'cat_pur_cat_pur_Auto', 'cat_pur_cat_pur_Baby', 'cat_pur_cat_pur_Bed_Bath_Table', 'cat_pur_cat_pur_Computers_Accessories', 'cat_pur_cat_pur_Consoles_Games', 'cat_pur_cat_pur_Cool_Stuff', 'cat_pur_cat_pur_Electronics', 'cat_pur_cat_pur_Fashion_Bags_Accessories', 'cat_pur_cat_pur_Furniture_Decor', 'cat_pur_cat_pur_Garden_Tools', 'cat_pur_cat_pur_Health_Beauty', 'cat_pur_cat_pur_Housewares', 'cat_pur_cat_pur_Luggage_Accessories', 'cat_pur_cat_pur_Office_Furniture', 'cat_pur_cat_pur_Perfumery', 'cat_pur_cat_pur_Pet_Shop', 'cat_pur_cat_pur_Sports_Leisure', 'cat_pur_cat_pur_Stationery', 'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys', 'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts', 'cat_pur_cat_pur_others', 'no_Distinct_categories', 'cat_cnt_first_purchase', 'total_act_amount', 'avg_basket_value', 'avg_margin', 'avg_quantity', 'avg_discount', 'avg_no_prds', 'buyer_flag', 'review_flag', 'multi_cat_flag', 'margin_pct', 'discount_pct']

In [1195]:
#promo_prd_pct=Promotional products percentage	
#---------------if no_prds = 0 then promo_prd_pct=.; else promo_prd_pct = no_prds_promo/no_prds;

In [1196]:
active_buyers['promo_prd_pct']=np.where(active_buyers['no_prods']==0,0,
                                        active_buyers['no_prds_promo']/active_buyers['no_prods'])

In [1197]:
print(f'{active_buyers.columns.to_list()}')

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix', 'geolocation_zip_code_prefix', 'order_item_id', 'product_id', 'seller_id', 'price', 'freight_value', 'payment_sequential', 'payment_installments', 'payment_value', 'review_score', 'product_category_name', 'seller_zip_code_prefix', 'total_amount', 'act_amt', 'cost_amt', 'margin', 'week_flag', 'promotion_flag', 'discount', 'product_group', 'first_purchase_flag', 'no_baskets', 'sale_amount', 'sale_amount_p1', 'sale_amount_p2', 'no_baskets_weekend', 'no_baskets_w_promo_prds', 'quantity', 'discount_item', 'no_prods', 'no_prds_weekend', 'no_prds_promo', 'cat_prd_cnt_Auto', 'cat_prd_cnt_Baby', 'cat_prd_cnt_Bed_Bath_Table', 'cat_prd_cnt_Computers_Accessories', 'cat_prd_cnt_Consoles_Games', 'cat_prd_cnt_Cool_Stuff', 'cat_prd_cnt_Electronics', 'cat_prd_cnt_Fashion_Bags_Accessories', 'cat_prd_cnt_Furniture_Decor', 'cat_prd_cnt_Garden_Tools', 'cat_prd_cnt_Health_Beauty', 'cat_prd_cnt_Housewares', 'cat_prd_cnt_Luggage_Accessories', 'cat_prd_cnt_Office_Furniture', 'cat_prd_cnt_Perfumery', 'cat_prd_cnt_Pet_Shop', 'cat_prd_cnt_Sports_Leisure', 'cat_prd_cnt_Stationery', 'cat_prd_cnt_Telephony', 'cat_prd_cnt_Toys', 'cat_prd_cnt_Unknown', 'cat_prd_cnt_Watches_Gifts', 'cat_prd_cnt_others', 'cat_amt_Auto', 'cat_amt_Baby', 'cat_amt_Bed_Bath_Table', 'cat_amt_Computers_Accessories', 'cat_amt_Consoles_Games', 'cat_amt_Cool_Stuff', 'cat_amt_Electronics', 'cat_amt_Fashion_Bags_Accessories', 'cat_amt_Furniture_Decor', 'cat_amt_Garden_Tools', 'cat_amt_Health_Beauty', 'cat_amt_Housewares', 'cat_amt_Luggage_Accessories', 'cat_amt_Office_Furniture', 'cat_amt_Perfumery', 'cat_amt_Pet_Shop', 'cat_amt_Sports_Leisure', 'cat_amt_Stationery', 'cat_amt_Telephony', 'cat_amt_Toys', 'cat_amt_Unknown', 'cat_amt_Watches_Gifts', 'cat_amt_others', 'cat_pen_Auto', 'cat_pen_Baby', 'cat_pen_Bed_Bath_Table', 'cat_pen_Computers_Accessories', 'cat_pen_Consoles_Games', 'cat_pen_Cool_Stuff', 'cat_pen_Electronics', 'cat_pen_Fashion_Bags_Accessories', 'cat_pen_Furniture_Decor', 'cat_pen_Garden_Tools', 'cat_pen_Health_Beauty', 'cat_pen_Housewares', 'cat_pen_Luggage_Accessories', 'cat_pen_Office_Furniture', 'cat_pen_Perfumery', 'cat_pen_Pet_Shop', 'cat_pen_Sports_Leisure', 'cat_pen_Stationery', 'cat_pen_Telephony', 'cat_pen_Toys', 'cat_pen_Unknown', 'cat_pen_Watches_Gifts', 'cat_pen_others', 'cat_pur_Auto', 'cat_pur_Baby', 'cat_pur_Bed_Bath_Table', 'cat_pur_Computers_Accessories', 'cat_pur_Consoles_Games', 'cat_pur_Cool_Stuff', 'cat_pur_Electronics', 'cat_pur_Fashion_Bags_Accessories', 'cat_pur_Furniture_Decor', 'cat_pur_Garden_Tools', 'cat_pur_Health_Beauty', 'cat_pur_Housewares', 'cat_pur_Luggage_Accessories', 'cat_pur_Office_Furniture', 'cat_pur_Perfumery', 'cat_pur_Pet_Shop', 'cat_pur_Sports_Leisure', 'cat_pur_Stationery', 'cat_pur_Telephony', 'cat_pur_Toys', 'cat_pur_Unknown', 'cat_pur_Watches_Gifts', 'cat_pur_others', 'cat_pur_cat_pur_Auto', 'cat_pur_cat_pur_Baby', 'cat_pur_cat_pur_Bed_Bath_Table', 'cat_pur_cat_pur_Computers_Accessories', 'cat_pur_cat_pur_Consoles_Games', 'cat_pur_cat_pur_Cool_Stuff', 'cat_pur_cat_pur_Electronics', 'cat_pur_cat_pur_Fashion_Bags_Accessories', 'cat_pur_cat_pur_Furniture_Decor', 'cat_pur_cat_pur_Garden_Tools', 'cat_pur_cat_pur_Health_Beauty', 'cat_pur_cat_pur_Housewares', 'cat_pur_cat_pur_Luggage_Accessories', 'cat_pur_cat_pur_Office_Furniture', 'cat_pur_cat_pur_Perfumery', 'cat_pur_cat_pur_Pet_Shop', 'cat_pur_cat_pur_Sports_Leisure', 'cat_pur_cat_pur_Stationery', 'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys', 'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts', 'cat_pur_cat_pur_others', 'no_Distinct_categories', 'cat_cnt_first_purchase', 'total_act_amount', 'avg_basket_value', 'avg_margin', 'avg_quantity', 'avg_discount', 'avg_no_prds', 'buyer_flag', 'review_flag', 'multi_cat_flag', 'margin_pct', 'discount_pct', 'promo_prd_pct']

In [1198]:
#pct_pur_w_promo_prds=Percentage of purchases(Trips/Baskets) with Promo samples	
#------if no_baskets > 0 then pct_pur_w_promo_prds = no_baskets_w_promo_prds/no_baskets;
#------else pct_pur_w_promo_prds = .;

In [1199]:
active_buyers['pct_pur_w_promo_prds']=np.where(active_buyers['no_baskets']>0,
                                              active_buyers['no_baskets_w_promo_prds']/active_buyers['no_baskets'],
                                              0)

In [1200]:
print(f'{active_buyers.columns.to_list()}')

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix', 'geolocation_zip_code_prefix', 'order_item_id', 'product_id', 'seller_id', 'price', 'freight_value', 'payment_sequential', 'payment_installments', 'payment_value', 'review_score', 'product_category_name', 'seller_zip_code_prefix', 'total_amount', 'act_amt', 'cost_amt', 'margin', 'week_flag', 'promotion_flag', 'discount', 'product_group', 'first_purchase_flag', 'no_baskets', 'sale_amount', 'sale_amount_p1', 'sale_amount_p2', 'no_baskets_weekend', 'no_baskets_w_promo_prds', 'quantity', 'discount_item', 'no_prods', 'no_prds_weekend', 'no_prds_promo', 'cat_prd_cnt_Auto', 'cat_prd_cnt_Baby', 'cat_prd_cnt_Bed_Bath_Table', 'cat_prd_cnt_Computers_Accessories', 'cat_prd_cnt_Consoles_Games', 'cat_prd_cnt_Cool_Stuff', 'cat_prd_cnt_Electronics', 'cat_prd_cnt_Fashion_Bags_Accessories', 'cat_prd_cnt_Furniture_Decor', 'cat_prd_cnt_Garden_Tools', 'cat_prd_cnt_Health_Beauty', 'cat_prd_cnt_Housewares', 'cat_prd_cnt_Luggage_Accessories', 'cat_prd_cnt_Office_Furniture', 'cat_prd_cnt_Perfumery', 'cat_prd_cnt_Pet_Shop', 'cat_prd_cnt_Sports_Leisure', 'cat_prd_cnt_Stationery', 'cat_prd_cnt_Telephony', 'cat_prd_cnt_Toys', 'cat_prd_cnt_Unknown', 'cat_prd_cnt_Watches_Gifts', 'cat_prd_cnt_others', 'cat_amt_Auto', 'cat_amt_Baby', 'cat_amt_Bed_Bath_Table', 'cat_amt_Computers_Accessories', 'cat_amt_Consoles_Games', 'cat_amt_Cool_Stuff', 'cat_amt_Electronics', 'cat_amt_Fashion_Bags_Accessories', 'cat_amt_Furniture_Decor', 'cat_amt_Garden_Tools', 'cat_amt_Health_Beauty', 'cat_amt_Housewares', 'cat_amt_Luggage_Accessories', 'cat_amt_Office_Furniture', 'cat_amt_Perfumery', 'cat_amt_Pet_Shop', 'cat_amt_Sports_Leisure', 'cat_amt_Stationery', 'cat_amt_Telephony', 'cat_amt_Toys', 'cat_amt_Unknown', 'cat_amt_Watches_Gifts', 'cat_amt_others', 'cat_pen_Auto', 'cat_pen_Baby', 'cat_pen_Bed_Bath_Table', 'cat_pen_Computers_Accessories', 'cat_pen_Consoles_Games', 'cat_pen_Cool_Stuff', 'cat_pen_Electronics', 'cat_pen_Fashion_Bags_Accessories', 'cat_pen_Furniture_Decor', 'cat_pen_Garden_Tools', 'cat_pen_Health_Beauty', 'cat_pen_Housewares', 'cat_pen_Luggage_Accessories', 'cat_pen_Office_Furniture', 'cat_pen_Perfumery', 'cat_pen_Pet_Shop', 'cat_pen_Sports_Leisure', 'cat_pen_Stationery', 'cat_pen_Telephony', 'cat_pen_Toys', 'cat_pen_Unknown', 'cat_pen_Watches_Gifts', 'cat_pen_others', 'cat_pur_Auto', 'cat_pur_Baby', 'cat_pur_Bed_Bath_Table', 'cat_pur_Computers_Accessories', 'cat_pur_Consoles_Games', 'cat_pur_Cool_Stuff', 'cat_pur_Electronics', 'cat_pur_Fashion_Bags_Accessories', 'cat_pur_Furniture_Decor', 'cat_pur_Garden_Tools', 'cat_pur_Health_Beauty', 'cat_pur_Housewares', 'cat_pur_Luggage_Accessories', 'cat_pur_Office_Furniture', 'cat_pur_Perfumery', 'cat_pur_Pet_Shop', 'cat_pur_Sports_Leisure', 'cat_pur_Stationery', 'cat_pur_Telephony', 'cat_pur_Toys', 'cat_pur_Unknown', 'cat_pur_Watches_Gifts', 'cat_pur_others', 'cat_pur_cat_pur_Auto', 'cat_pur_cat_pur_Baby', 'cat_pur_cat_pur_Bed_Bath_Table', 'cat_pur_cat_pur_Computers_Accessories', 'cat_pur_cat_pur_Consoles_Games', 'cat_pur_cat_pur_Cool_Stuff', 'cat_pur_cat_pur_Electronics', 'cat_pur_cat_pur_Fashion_Bags_Accessories', 'cat_pur_cat_pur_Furniture_Decor', 'cat_pur_cat_pur_Garden_Tools', 'cat_pur_cat_pur_Health_Beauty', 'cat_pur_cat_pur_Housewares', 'cat_pur_cat_pur_Luggage_Accessories', 'cat_pur_cat_pur_Office_Furniture', 'cat_pur_cat_pur_Perfumery', 'cat_pur_cat_pur_Pet_Shop', 'cat_pur_cat_pur_Sports_Leisure', 'cat_pur_cat_pur_Stationery', 'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys', 'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts', 'cat_pur_cat_pur_others', 'no_Distinct_categories', 'cat_cnt_first_purchase', 'total_act_amount', 'avg_basket_value', 'avg_margin', 'avg_quantity', 'avg_discount', 'avg_no_prds', 'buyer_flag', 'review_flag', 'multi_cat_flag', 'margin_pct', 'discount_pct', 'promo_prd_pct', 'pct_pur_w_promo_prds']

In [1201]:
#Promo_seeker_flag=Promo seeker	
#--------if pct_pur_w_promo_prds <= 0.8 and promo_prd_pct <= 0.5 then Promo_seeker = 0; 
#--------else Promo_seeker = 1;

In [1202]:
active_buyers['promo_seeker_flag']=np.where((active_buyers['pct_pur_w_promo_prds']<=0.8) &\
                                            (active_buyers['promo_prd_pct']<=0.5),0,1)

In [1203]:
print(f'{active_buyers.columns.to_list()}')

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix', 'geolocation_zip_code_prefix', 'order_item_id', 'product_id', 'seller_id', 'price', 'freight_value', 'payment_sequential', 'payment_installments', 'payment_value', 'review_score', 'product_category_name', 'seller_zip_code_prefix', 'total_amount', 'act_amt', 'cost_amt', 'margin', 'week_flag', 'promotion_flag', 'discount', 'product_group', 'first_purchase_flag', 'no_baskets', 'sale_amount', 'sale_amount_p1', 'sale_amount_p2', 'no_baskets_weekend', 'no_baskets_w_promo_prds', 'quantity', 'discount_item', 'no_prods', 'no_prds_weekend', 'no_prds_promo', 'cat_prd_cnt_Auto', 'cat_prd_cnt_Baby', 'cat_prd_cnt_Bed_Bath_Table', 'cat_prd_cnt_Computers_Accessories', 'cat_prd_cnt_Consoles_Games', 'cat_prd_cnt_Cool_Stuff', 'cat_prd_cnt_Electronics', 'cat_prd_cnt_Fashion_Bags_Accessories', 'cat_prd_cnt_Furniture_Decor', 'cat_prd_cnt_Garden_Tools', 'cat_prd_cnt_Health_Beauty', 'cat_prd_cnt_Housewares', 'cat_prd_cnt_Luggage_Accessories', 'cat_prd_cnt_Office_Furniture', 'cat_prd_cnt_Perfumery', 'cat_prd_cnt_Pet_Shop', 'cat_prd_cnt_Sports_Leisure', 'cat_prd_cnt_Stationery', 'cat_prd_cnt_Telephony', 'cat_prd_cnt_Toys', 'cat_prd_cnt_Unknown', 'cat_prd_cnt_Watches_Gifts', 'cat_prd_cnt_others', 'cat_amt_Auto', 'cat_amt_Baby', 'cat_amt_Bed_Bath_Table', 'cat_amt_Computers_Accessories', 'cat_amt_Consoles_Games', 'cat_amt_Cool_Stuff', 'cat_amt_Electronics', 'cat_amt_Fashion_Bags_Accessories', 'cat_amt_Furniture_Decor', 'cat_amt_Garden_Tools', 'cat_amt_Health_Beauty', 'cat_amt_Housewares', 'cat_amt_Luggage_Accessories', 'cat_amt_Office_Furniture', 'cat_amt_Perfumery', 'cat_amt_Pet_Shop', 'cat_amt_Sports_Leisure', 'cat_amt_Stationery', 'cat_amt_Telephony', 'cat_amt_Toys', 'cat_amt_Unknown', 'cat_amt_Watches_Gifts', 'cat_amt_others', 'cat_pen_Auto', 'cat_pen_Baby', 'cat_pen_Bed_Bath_Table', 'cat_pen_Computers_Accessories', 'cat_pen_Consoles_Games', 'cat_pen_Cool_Stuff', 'cat_pen_Electronics', 'cat_pen_Fashion_Bags_Accessories', 'cat_pen_Furniture_Decor', 'cat_pen_Garden_Tools', 'cat_pen_Health_Beauty', 'cat_pen_Housewares', 'cat_pen_Luggage_Accessories', 'cat_pen_Office_Furniture', 'cat_pen_Perfumery', 'cat_pen_Pet_Shop', 'cat_pen_Sports_Leisure', 'cat_pen_Stationery', 'cat_pen_Telephony', 'cat_pen_Toys', 'cat_pen_Unknown', 'cat_pen_Watches_Gifts', 'cat_pen_others', 'cat_pur_Auto', 'cat_pur_Baby', 'cat_pur_Bed_Bath_Table', 'cat_pur_Computers_Accessories', 'cat_pur_Consoles_Games', 'cat_pur_Cool_Stuff', 'cat_pur_Electronics', 'cat_pur_Fashion_Bags_Accessories', 'cat_pur_Furniture_Decor', 'cat_pur_Garden_Tools', 'cat_pur_Health_Beauty', 'cat_pur_Housewares', 'cat_pur_Luggage_Accessories', 'cat_pur_Office_Furniture', 'cat_pur_Perfumery', 'cat_pur_Pet_Shop', 'cat_pur_Sports_Leisure', 'cat_pur_Stationery', 'cat_pur_Telephony', 'cat_pur_Toys', 'cat_pur_Unknown', 'cat_pur_Watches_Gifts', 'cat_pur_others', 'cat_pur_cat_pur_Auto', 'cat_pur_cat_pur_Baby', 'cat_pur_cat_pur_Bed_Bath_Table', 'cat_pur_cat_pur_Computers_Accessories', 'cat_pur_cat_pur_Consoles_Games', 'cat_pur_cat_pur_Cool_Stuff', 'cat_pur_cat_pur_Electronics', 'cat_pur_cat_pur_Fashion_Bags_Accessories', 'cat_pur_cat_pur_Furniture_Decor', 'cat_pur_cat_pur_Garden_Tools', 'cat_pur_cat_pur_Health_Beauty', 'cat_pur_cat_pur_Housewares', 'cat_pur_cat_pur_Luggage_Accessories', 'cat_pur_cat_pur_Office_Furniture', 'cat_pur_cat_pur_Perfumery', 'cat_pur_cat_pur_Pet_Shop', 'cat_pur_cat_pur_Sports_Leisure', 'cat_pur_cat_pur_Stationery', 'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys', 'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts', 'cat_pur_cat_pur_others', 'no_Distinct_categories', 'cat_cnt_first_purchase', 'total_act_amount', 'avg_basket_value', 'avg_margin', 'avg_quantity', 'avg_discount', 'avg_no_prds', 'buyer_flag', 'review_flag', 'multi_cat_flag', 'margin_pct', 'discount_pct', 'promo_prd_pct', 'pct_pur_w_promo_prds', 'promo_seeker_flag']

In [1204]:
#Decile_payment_installments=Value Decile Flag based on payment_installments (0-9 Deciles)

In [1208]:
active_buyers['decile_payment_installments']=pd.qcut(active_buyers['payment_installments'],
                                                     10,labels=False,duplicates='drop')

In [1209]:
print(f'{active_buyers.columns.to_list()}')

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix', 'geolocation_zip_code_prefix', 'order_item_id', 'product_id', 'seller_id', 'price', 'freight_value', 'payment_sequential', 'payment_installments', 'payment_value', 'review_score', 'product_category_name', 'seller_zip_code_prefix', 'total_amount', 'act_amt', 'cost_amt', 'margin', 'week_flag', 'promotion_flag', 'discount', 'product_group', 'first_purchase_flag', 'no_baskets', 'sale_amount', 'sale_amount_p1', 'sale_amount_p2', 'no_baskets_weekend', 'no_baskets_w_promo_prds', 'quantity', 'discount_item', 'no_prods', 'no_prds_weekend', 'no_prds_promo', 'cat_prd_cnt_Auto', 'cat_prd_cnt_Baby', 'cat_prd_cnt_Bed_Bath_Table', 'cat_prd_cnt_Computers_Accessories', 'cat_prd_cnt_Consoles_Games', 'cat_prd_cnt_Cool_Stuff', 'cat_prd_cnt_Electronics', 'cat_prd_cnt_Fashion_Bags_Accessories', 'cat_prd_cnt_Furniture_Decor', 'cat_prd_cnt_Garden_Tools', 'cat_prd_cnt_Health_Beauty', 'cat_prd_cnt_Housewares', 'cat_prd_cnt_Luggage_Accessories', 'cat_prd_cnt_Office_Furniture', 'cat_prd_cnt_Perfumery', 'cat_prd_cnt_Pet_Shop', 'cat_prd_cnt_Sports_Leisure', 'cat_prd_cnt_Stationery', 'cat_prd_cnt_Telephony', 'cat_prd_cnt_Toys', 'cat_prd_cnt_Unknown', 'cat_prd_cnt_Watches_Gifts', 'cat_prd_cnt_others', 'cat_amt_Auto', 'cat_amt_Baby', 'cat_amt_Bed_Bath_Table', 'cat_amt_Computers_Accessories', 'cat_amt_Consoles_Games', 'cat_amt_Cool_Stuff', 'cat_amt_Electronics', 'cat_amt_Fashion_Bags_Accessories', 'cat_amt_Furniture_Decor', 'cat_amt_Garden_Tools', 'cat_amt_Health_Beauty', 'cat_amt_Housewares', 'cat_amt_Luggage_Accessories', 'cat_amt_Office_Furniture', 'cat_amt_Perfumery', 'cat_amt_Pet_Shop', 'cat_amt_Sports_Leisure', 'cat_amt_Stationery', 'cat_amt_Telephony', 'cat_amt_Toys', 'cat_amt_Unknown', 'cat_amt_Watches_Gifts', 'cat_amt_others', 'cat_pen_Auto', 'cat_pen_Baby', 'cat_pen_Bed_Bath_Table', 'cat_pen_Computers_Accessories', 'cat_pen_Consoles_Games', 'cat_pen_Cool_Stuff', 'cat_pen_Electronics', 'cat_pen_Fashion_Bags_Accessories', 'cat_pen_Furniture_Decor', 'cat_pen_Garden_Tools', 'cat_pen_Health_Beauty', 'cat_pen_Housewares', 'cat_pen_Luggage_Accessories', 'cat_pen_Office_Furniture', 'cat_pen_Perfumery', 'cat_pen_Pet_Shop', 'cat_pen_Sports_Leisure', 'cat_pen_Stationery', 'cat_pen_Telephony', 'cat_pen_Toys', 'cat_pen_Unknown', 'cat_pen_Watches_Gifts', 'cat_pen_others', 'cat_pur_Auto', 'cat_pur_Baby', 'cat_pur_Bed_Bath_Table', 'cat_pur_Computers_Accessories', 'cat_pur_Consoles_Games', 'cat_pur_Cool_Stuff', 'cat_pur_Electronics', 'cat_pur_Fashion_Bags_Accessories', 'cat_pur_Furniture_Decor', 'cat_pur_Garden_Tools', 'cat_pur_Health_Beauty', 'cat_pur_Housewares', 'cat_pur_Luggage_Accessories', 'cat_pur_Office_Furniture', 'cat_pur_Perfumery', 'cat_pur_Pet_Shop', 'cat_pur_Sports_Leisure', 'cat_pur_Stationery', 'cat_pur_Telephony', 'cat_pur_Toys', 'cat_pur_Unknown', 'cat_pur_Watches_Gifts', 'cat_pur_others', 'cat_pur_cat_pur_Auto', 'cat_pur_cat_pur_Baby', 'cat_pur_cat_pur_Bed_Bath_Table', 'cat_pur_cat_pur_Computers_Accessories', 'cat_pur_cat_pur_Consoles_Games', 'cat_pur_cat_pur_Cool_Stuff', 'cat_pur_cat_pur_Electronics', 'cat_pur_cat_pur_Fashion_Bags_Accessories', 'cat_pur_cat_pur_Furniture_Decor', 'cat_pur_cat_pur_Garden_Tools', 'cat_pur_cat_pur_Health_Beauty', 'cat_pur_cat_pur_Housewares', 'cat_pur_cat_pur_Luggage_Accessories', 'cat_pur_cat_pur_Office_Furniture', 'cat_pur_cat_pur_Perfumery', 'cat_pur_cat_pur_Pet_Shop', 'cat_pur_cat_pur_Sports_Leisure', 'cat_pur_cat_pur_Stationery', 'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys', 'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts', 'cat_pur_cat_pur_others', 'no_Distinct_categories', 'cat_cnt_first_purchase', 'total_act_amount', 'avg_basket_value', 'avg_margin', 'avg_quantity', 'avg_discount', 'avg_no_prds', 'buyer_flag', 'review_flag', 'multi_cat_flag', 'margin_pct', 'discount_pct', 'promo_prd_pct', 'pct_pur_w_promo_prds', 'promo_seeker_flag', 'decile_payment_installments']

In [1210]:
#CustomerSegment=Customer Segment (New, Churner, UpwardMigrator, Downward Migrator)	
#----"New = if sales_amount_p1 = 0 and sales_amount_p2 >0, 
#----Churn= if sales_amount_p1 >0 and sales_amount_p2=0
#----UpwardMigrator = if sales_amount_p2 > sales_amount_p1
#----DownWardMigrator = if sales_amount_p1 >sales_amount_p2"

In [1216]:
active_buyers.loc[:,('sale_amount_p1','sale_amount_p2')]

        sale_amount_p1  sale_amount_p2
0                38.71            0.00
1                38.71            0.00
2                38.71            0.00
3                 0.00          141.46
4                 0.00          179.12
...                ...             ...
118737            0.00          195.00
118738          271.01            0.00
118739            0.00          882.32
118740            0.00          882.32
118741            0.00           86.86

[118742 rows x 2 columns]

In [1233]:
active_buyers['customerSegment']=\
        np.where(((active_buyers['sale_amount_p1']==0)&(active_buyers['sale_amount_p2']>0)),\
                 'new',\
        np.where(((active_buyers['sale_amount_p1']>0)&(active_buyers['sale_amount_p2']==0)),\
                 'churn',\
        np.where((active_buyers['sale_amount_p2']> active_buyers['sale_amount_p1']),\
                 'upwardMigrator',\
        np.where((active_buyers['sale_amount_p1']>active_buyers['sale_amount_p2']),\
                 'downwardMigrator','unknown'
                )
                )
                )
                )

In [1234]:
print(f'{active_buyers.columns.to_list()}')

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix', 'geolocation_zip_code_prefix', 'order_item_id', 'product_id', 'seller_id', 'price', 'freight_value', 'payment_sequential', 'payment_installments', 'payment_value', 'review_score', 'product_category_name', 'seller_zip_code_prefix', 'total_amount', 'act_amt', 'cost_amt', 'margin', 'week_flag', 'promotion_flag', 'discount', 'product_group', 'first_purchase_flag', 'no_baskets', 'sale_amount', 'sale_amount_p1', 'sale_amount_p2', 'no_baskets_weekend', 'no_baskets_w_promo_prds', 'quantity', 'discount_item', 'no_prods', 'no_prds_weekend', 'no_prds_promo', 'cat_prd_cnt_Auto', 'cat_prd_cnt_Baby', 'cat_prd_cnt_Bed_Bath_Table', 'cat_prd_cnt_Computers_Accessories', 'cat_prd_cnt_Consoles_Games', 'cat_prd_cnt_Cool_Stuff', 'cat_prd_cnt_Electronics', 'cat_prd_cnt_Fashion_Bags_Accessories', 'cat_prd_cnt_Furniture_Decor', 'cat_prd_cnt_Garden_Tools', 'cat_prd_cnt_Health_Beauty', 'cat_prd_cnt_Housewares', 'cat_prd_cnt_Luggage_Accessories', 'cat_prd_cnt_Office_Furniture', 'cat_prd_cnt_Perfumery', 'cat_prd_cnt_Pet_Shop', 'cat_prd_cnt_Sports_Leisure', 'cat_prd_cnt_Stationery', 'cat_prd_cnt_Telephony', 'cat_prd_cnt_Toys', 'cat_prd_cnt_Unknown', 'cat_prd_cnt_Watches_Gifts', 'cat_prd_cnt_others', 'cat_amt_Auto', 'cat_amt_Baby', 'cat_amt_Bed_Bath_Table', 'cat_amt_Computers_Accessories', 'cat_amt_Consoles_Games', 'cat_amt_Cool_Stuff', 'cat_amt_Electronics', 'cat_amt_Fashion_Bags_Accessories', 'cat_amt_Furniture_Decor', 'cat_amt_Garden_Tools', 'cat_amt_Health_Beauty', 'cat_amt_Housewares', 'cat_amt_Luggage_Accessories', 'cat_amt_Office_Furniture', 'cat_amt_Perfumery', 'cat_amt_Pet_Shop', 'cat_amt_Sports_Leisure', 'cat_amt_Stationery', 'cat_amt_Telephony', 'cat_amt_Toys', 'cat_amt_Unknown', 'cat_amt_Watches_Gifts', 'cat_amt_others', 'cat_pen_Auto', 'cat_pen_Baby', 'cat_pen_Bed_Bath_Table', 'cat_pen_Computers_Accessories', 'cat_pen_Consoles_Games', 'cat_pen_Cool_Stuff', 'cat_pen_Electronics', 'cat_pen_Fashion_Bags_Accessories', 'cat_pen_Furniture_Decor', 'cat_pen_Garden_Tools', 'cat_pen_Health_Beauty', 'cat_pen_Housewares', 'cat_pen_Luggage_Accessories', 'cat_pen_Office_Furniture', 'cat_pen_Perfumery', 'cat_pen_Pet_Shop', 'cat_pen_Sports_Leisure', 'cat_pen_Stationery', 'cat_pen_Telephony', 'cat_pen_Toys', 'cat_pen_Unknown', 'cat_pen_Watches_Gifts', 'cat_pen_others', 'cat_pur_Auto', 'cat_pur_Baby', 'cat_pur_Bed_Bath_Table', 'cat_pur_Computers_Accessories', 'cat_pur_Consoles_Games', 'cat_pur_Cool_Stuff', 'cat_pur_Electronics', 'cat_pur_Fashion_Bags_Accessories', 'cat_pur_Furniture_Decor', 'cat_pur_Garden_Tools', 'cat_pur_Health_Beauty', 'cat_pur_Housewares', 'cat_pur_Luggage_Accessories', 'cat_pur_Office_Furniture', 'cat_pur_Perfumery', 'cat_pur_Pet_Shop', 'cat_pur_Sports_Leisure', 'cat_pur_Stationery', 'cat_pur_Telephony', 'cat_pur_Toys', 'cat_pur_Unknown', 'cat_pur_Watches_Gifts', 'cat_pur_others', 'cat_pur_cat_pur_Auto', 'cat_pur_cat_pur_Baby', 'cat_pur_cat_pur_Bed_Bath_Table', 'cat_pur_cat_pur_Computers_Accessories', 'cat_pur_cat_pur_Consoles_Games', 'cat_pur_cat_pur_Cool_Stuff', 'cat_pur_cat_pur_Electronics', 'cat_pur_cat_pur_Fashion_Bags_Accessories', 'cat_pur_cat_pur_Furniture_Decor', 'cat_pur_cat_pur_Garden_Tools', 'cat_pur_cat_pur_Health_Beauty', 'cat_pur_cat_pur_Housewares', 'cat_pur_cat_pur_Luggage_Accessories', 'cat_pur_cat_pur_Office_Furniture', 'cat_pur_cat_pur_Perfumery', 'cat_pur_cat_pur_Pet_Shop', 'cat_pur_cat_pur_Sports_Leisure', 'cat_pur_cat_pur_Stationery', 'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys', 'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts', 'cat_pur_cat_pur_others', 'no_Distinct_categories', 'cat_cnt_first_purchase', 'total_act_amount', 'avg_basket_value', 'avg_margin', 'avg_quantity', 'avg_discount', 'avg_no_prds', 'buyer_flag', 'review_flag', 'multi_cat_flag', 'margin_pct', 'discount_pct', 'promo_prd_pct', 'pct_pur_w_promo_prds', 'promo_seeker_flag', 'decile_payment_installments', 'customerSegment']

In [ ]:
#Churn_flag=Churn customers	Churn
#-----------Churn if sales_amount_p1 >0 and sales_amount_p2=0

In [1239]:
active_buyers['churn_flag']=np.where((active_buyers['sale_amount_p1']>0) & (active_buyers['sale_amount_p2']==0),\
                                   'churn','0')

In [1240]:
print(f'{active_buyers.columns.to_list()}')

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix', 'geolocation_zip_code_prefix', 'order_item_id', 'product_id', 'seller_id', 'price', 'freight_value', 'payment_sequential', 'payment_installments', 'payment_value', 'review_score', 'product_category_name', 'seller_zip_code_prefix', 'total_amount', 'act_amt', 'cost_amt', 'margin', 'week_flag', 'promotion_flag', 'discount', 'product_group', 'first_purchase_flag', 'no_baskets', 'sale_amount', 'sale_amount_p1', 'sale_amount_p2', 'no_baskets_weekend', 'no_baskets_w_promo_prds', 'quantity', 'discount_item', 'no_prods', 'no_prds_weekend', 'no_prds_promo', 'cat_prd_cnt_Auto', 'cat_prd_cnt_Baby', 'cat_prd_cnt_Bed_Bath_Table', 'cat_prd_cnt_Computers_Accessories', 'cat_prd_cnt_Consoles_Games', 'cat_prd_cnt_Cool_Stuff', 'cat_prd_cnt_Electronics', 'cat_prd_cnt_Fashion_Bags_Accessories', 'cat_prd_cnt_Furniture_Decor', 'cat_prd_cnt_Garden_Tools', 'cat_prd_cnt_Health_Beauty', 'cat_prd_cnt_Housewares', 'cat_prd_cnt_Luggage_Accessories', 'cat_prd_cnt_Office_Furniture', 'cat_prd_cnt_Perfumery', 'cat_prd_cnt_Pet_Shop', 'cat_prd_cnt_Sports_Leisure', 'cat_prd_cnt_Stationery', 'cat_prd_cnt_Telephony', 'cat_prd_cnt_Toys', 'cat_prd_cnt_Unknown', 'cat_prd_cnt_Watches_Gifts', 'cat_prd_cnt_others', 'cat_amt_Auto', 'cat_amt_Baby', 'cat_amt_Bed_Bath_Table', 'cat_amt_Computers_Accessories', 'cat_amt_Consoles_Games', 'cat_amt_Cool_Stuff', 'cat_amt_Electronics', 'cat_amt_Fashion_Bags_Accessories', 'cat_amt_Furniture_Decor', 'cat_amt_Garden_Tools', 'cat_amt_Health_Beauty', 'cat_amt_Housewares', 'cat_amt_Luggage_Accessories', 'cat_amt_Office_Furniture', 'cat_amt_Perfumery', 'cat_amt_Pet_Shop', 'cat_amt_Sports_Leisure', 'cat_amt_Stationery', 'cat_amt_Telephony', 'cat_amt_Toys', 'cat_amt_Unknown', 'cat_amt_Watches_Gifts', 'cat_amt_others', 'cat_pen_Auto', 'cat_pen_Baby', 'cat_pen_Bed_Bath_Table', 'cat_pen_Computers_Accessories', 'cat_pen_Consoles_Games', 'cat_pen_Cool_Stuff', 'cat_pen_Electronics', 'cat_pen_Fashion_Bags_Accessories', 'cat_pen_Furniture_Decor', 'cat_pen_Garden_Tools', 'cat_pen_Health_Beauty', 'cat_pen_Housewares', 'cat_pen_Luggage_Accessories', 'cat_pen_Office_Furniture', 'cat_pen_Perfumery', 'cat_pen_Pet_Shop', 'cat_pen_Sports_Leisure', 'cat_pen_Stationery', 'cat_pen_Telephony', 'cat_pen_Toys', 'cat_pen_Unknown', 'cat_pen_Watches_Gifts', 'cat_pen_others', 'cat_pur_Auto', 'cat_pur_Baby', 'cat_pur_Bed_Bath_Table', 'cat_pur_Computers_Accessories', 'cat_pur_Consoles_Games', 'cat_pur_Cool_Stuff', 'cat_pur_Electronics', 'cat_pur_Fashion_Bags_Accessories', 'cat_pur_Furniture_Decor', 'cat_pur_Garden_Tools', 'cat_pur_Health_Beauty', 'cat_pur_Housewares', 'cat_pur_Luggage_Accessories', 'cat_pur_Office_Furniture', 'cat_pur_Perfumery', 'cat_pur_Pet_Shop', 'cat_pur_Sports_Leisure', 'cat_pur_Stationery', 'cat_pur_Telephony', 'cat_pur_Toys', 'cat_pur_Unknown', 'cat_pur_Watches_Gifts', 'cat_pur_others', 'cat_pur_cat_pur_Auto', 'cat_pur_cat_pur_Baby', 'cat_pur_cat_pur_Bed_Bath_Table', 'cat_pur_cat_pur_Computers_Accessories', 'cat_pur_cat_pur_Consoles_Games', 'cat_pur_cat_pur_Cool_Stuff', 'cat_pur_cat_pur_Electronics', 'cat_pur_cat_pur_Fashion_Bags_Accessories', 'cat_pur_cat_pur_Furniture_Decor', 'cat_pur_cat_pur_Garden_Tools', 'cat_pur_cat_pur_Health_Beauty', 'cat_pur_cat_pur_Housewares', 'cat_pur_cat_pur_Luggage_Accessories', 'cat_pur_cat_pur_Office_Furniture', 'cat_pur_cat_pur_Perfumery', 'cat_pur_cat_pur_Pet_Shop', 'cat_pur_cat_pur_Sports_Leisure', 'cat_pur_cat_pur_Stationery', 'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys', 'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts', 'cat_pur_cat_pur_others', 'no_Distinct_categories', 'cat_cnt_first_purchase', 'total_act_amount', 'avg_basket_value', 'avg_margin', 'avg_quantity', 'avg_discount', 'avg_no_prds', 'buyer_flag', 'review_flag', 'multi_cat_flag', 'margin_pct', 'discount_pct', 'promo_prd_pct', 'pct_pur_w_promo_prds', 'promo_seeker_flag', 'decile_payment_installments', 'customerSegment', 'churn_flag']

In [ ]:
#High_Spender_flag=
#------------if Decile_payment_installments=9, then High_spender_flag=1 else 0

In [1241]:
active_buyers['high_Spender_flag']=np.where(active_buyers['decile_payment_installments']==9,
                                           1,0)

In [1242]:
print(f'{active_buyers.columns.to_list()}')

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'order_purchase_timestamp_period_flag', 'customer_zip_code_prefix', 'geolocation_zip_code_prefix', 'order_item_id', 'product_id', 'seller_id', 'price', 'freight_value', 'payment_sequential', 'payment_installments', 'payment_value', 'review_score', 'product_category_name', 'seller_zip_code_prefix', 'total_amount', 'act_amt', 'cost_amt', 'margin', 'week_flag', 'promotion_flag', 'discount', 'product_group', 'first_purchase_flag', 'no_baskets', 'sale_amount', 'sale_amount_p1', 'sale_amount_p2', 'no_baskets_weekend', 'no_baskets_w_promo_prds', 'quantity', 'discount_item', 'no_prods', 'no_prds_weekend', 'no_prds_promo', 'cat_prd_cnt_Auto', 'cat_prd_cnt_Baby', 'cat_prd_cnt_Bed_Bath_Table', 'cat_prd_cnt_Computers_Accessories', 'cat_prd_cnt_Consoles_Games', 'cat_prd_cnt_Cool_Stuff', 'cat_prd_cnt_Electronics', 'cat_prd_cnt_Fashion_Bags_Accessories', 'cat_prd_cnt_Furniture_Decor', 'cat_prd_cnt_Garden_Tools', 'cat_prd_cnt_Health_Beauty', 'cat_prd_cnt_Housewares', 'cat_prd_cnt_Luggage_Accessories', 'cat_prd_cnt_Office_Furniture', 'cat_prd_cnt_Perfumery', 'cat_prd_cnt_Pet_Shop', 'cat_prd_cnt_Sports_Leisure', 'cat_prd_cnt_Stationery', 'cat_prd_cnt_Telephony', 'cat_prd_cnt_Toys', 'cat_prd_cnt_Unknown', 'cat_prd_cnt_Watches_Gifts', 'cat_prd_cnt_others', 'cat_amt_Auto', 'cat_amt_Baby', 'cat_amt_Bed_Bath_Table', 'cat_amt_Computers_Accessories', 'cat_amt_Consoles_Games', 'cat_amt_Cool_Stuff', 'cat_amt_Electronics', 'cat_amt_Fashion_Bags_Accessories', 'cat_amt_Furniture_Decor', 'cat_amt_Garden_Tools', 'cat_amt_Health_Beauty', 'cat_amt_Housewares', 'cat_amt_Luggage_Accessories', 'cat_amt_Office_Furniture', 'cat_amt_Perfumery', 'cat_amt_Pet_Shop', 'cat_amt_Sports_Leisure', 'cat_amt_Stationery', 'cat_amt_Telephony', 'cat_amt_Toys', 'cat_amt_Unknown', 'cat_amt_Watches_Gifts', 'cat_amt_others', 'cat_pen_Auto', 'cat_pen_Baby', 'cat_pen_Bed_Bath_Table', 'cat_pen_Computers_Accessories', 'cat_pen_Consoles_Games', 'cat_pen_Cool_Stuff', 'cat_pen_Electronics', 'cat_pen_Fashion_Bags_Accessories', 'cat_pen_Furniture_Decor', 'cat_pen_Garden_Tools', 'cat_pen_Health_Beauty', 'cat_pen_Housewares', 'cat_pen_Luggage_Accessories', 'cat_pen_Office_Furniture', 'cat_pen_Perfumery', 'cat_pen_Pet_Shop', 'cat_pen_Sports_Leisure', 'cat_pen_Stationery', 'cat_pen_Telephony', 'cat_pen_Toys', 'cat_pen_Unknown', 'cat_pen_Watches_Gifts', 'cat_pen_others', 'cat_pur_Auto', 'cat_pur_Baby', 'cat_pur_Bed_Bath_Table', 'cat_pur_Computers_Accessories', 'cat_pur_Consoles_Games', 'cat_pur_Cool_Stuff', 'cat_pur_Electronics', 'cat_pur_Fashion_Bags_Accessories', 'cat_pur_Furniture_Decor', 'cat_pur_Garden_Tools', 'cat_pur_Health_Beauty', 'cat_pur_Housewares', 'cat_pur_Luggage_Accessories', 'cat_pur_Office_Furniture', 'cat_pur_Perfumery', 'cat_pur_Pet_Shop', 'cat_pur_Sports_Leisure', 'cat_pur_Stationery', 'cat_pur_Telephony', 'cat_pur_Toys', 'cat_pur_Unknown', 'cat_pur_Watches_Gifts', 'cat_pur_others', 'cat_pur_cat_pur_Auto', 'cat_pur_cat_pur_Baby', 'cat_pur_cat_pur_Bed_Bath_Table', 'cat_pur_cat_pur_Computers_Accessories', 'cat_pur_cat_pur_Consoles_Games', 'cat_pur_cat_pur_Cool_Stuff', 'cat_pur_cat_pur_Electronics', 'cat_pur_cat_pur_Fashion_Bags_Accessories', 'cat_pur_cat_pur_Furniture_Decor', 'cat_pur_cat_pur_Garden_Tools', 'cat_pur_cat_pur_Health_Beauty', 'cat_pur_cat_pur_Housewares', 'cat_pur_cat_pur_Luggage_Accessories', 'cat_pur_cat_pur_Office_Furniture', 'cat_pur_cat_pur_Perfumery', 'cat_pur_cat_pur_Pet_Shop', 'cat_pur_cat_pur_Sports_Leisure', 'cat_pur_cat_pur_Stationery', 'cat_pur_cat_pur_Telephony', 'cat_pur_cat_pur_Toys', 'cat_pur_cat_pur_Unknown', 'cat_pur_cat_pur_Watches_Gifts', 'cat_pur_cat_pur_others', 'no_Distinct_categories', 'cat_cnt_first_purchase', 'total_act_amount', 'avg_basket_value', 'avg_margin', 'avg_quantity', 'avg_discount', 'avg_no_prds', 'buyer_flag', 'review_flag', 'multi_cat_flag', 'margin_pct', 'discount_pct', 'promo_prd_pct', 'pct_pur_w_promo_prds', 'promo_seeker_flag', 'decile_payment_installments', 'customerSegment', 'churn_flag', 'high_Spender_flag']

In [1243]:
active_buyers.to_csv('C://Users//sneha//anaconda_projects//Customer_360//active_buyers.csv',index=False)